### ISSUE TITLE
Possible to do it via command line?

### ISSUE THREAD

**Issue by DatDraggy** [konklone/json#105]
Hello, 
I am trying to convert a 60 and a 80MB file but it takes too long and don't even know if it's working. is there maybe a way I can convert a jsons file to csv via the windows or linux command prompt? Or do you maybe have a dev version where I can upload a file so it doesn't display in browser? The smaller file already has 200k json blocks...
Also a little bug report, you can't download on Chrome. it says network error.
I got the first part of the file done when i splitted it but the second part doesnt work. The first box where I entered it formats it correctly but nothing appears at the bottom one even after waiting some time. They both have the same length

**Comment by WInf9Kieran** [comment]
Welp nvm. The link doesn't fully work. I'm really confused why it doesnt work

**Comment by konklone** [comment]
Sorry, that's out of scope for this project. :/ You can try [csvkit](https://csvkit.readthedocs.io/en/0.9.1/) to see if that can offer you something. It has an `in2csv` command, but it doesn't handle nested JSON blocks the same way as my in-browser version does.
