### ISSUE TITLE
Error parsing some specific JSON

### ISSUE THREAD

**Issue by helteixeira** [konklone/json#107]
I'm having an issue converting this JSON:

https://konklone.io/json/?id=ebb264805c5b03a28cc07b8c7f199300

``` json
https://api.worldoftanks.eu/wot/account/info/?application_id=demo&account_id=[REDACTED]
```

**Comment by konklone** [comment]
This is a URL, not JSON. 

(Edit: I redacted the `account_id` in the URL above.)
