### ISSUE TITLE
Spanish issues

### ISSUE THREAD

**Issue by csacanam** [konklone/json#110]
There is an issue related with encoding. For example CAROL ANDREA SANCHEZ MUÃ‘OZ instead of CAROL ANDRES SANCHEZ MUÑOZ.  I think it could be solved adding UTF-8 as the encoding format.

**Comment by konklone** [comment]
@csacanam It looks fine for me. Here's a permalink to a test:

https://konklone.io/json/?id=af2ca17b78a34a52dd3125f7ca4f494d

Recognized in the input area:

<img width="456" alt="screen shot 2016-11-01 at 1 21 59 am" src="https://cloud.githubusercontent.com/assets/4592/19880205/a99f8802-9fd1-11e6-82b5-d09c091a9970.png">

Recognized in the preview area:

<img width="421" alt="screen shot 2016-11-01 at 1 22 03 am" src="https://cloud.githubusercontent.com/assets/4592/19880210/af02258e-9fd1-11e6-9a7e-fc3a79129615.png">

Recognized in the `Preview` app when viewing the downloaded CSV:

<img width="422" alt="screen shot 2016-11-01 at 1 22 12 am" src="https://cloud.githubusercontent.com/assets/4592/19880213/b72a14c4-9fd1-11e6-969d-550e532dfa3c.png">

This is on Chrome in OS X.
