### ISSUE TITLE
Mention/document browser download limits

### ISSUE THREAD

**Issue by DavidLangevin** [konklone/json#120]
I get a network error : http://screencast.com/t/77wggW3R4

**Comment by konklone** [comment]
Can you try in Firefox and see if that works?

No CSV data is transferred over the network -- everything is local.

**Comment by evgrud** [comment]
It has to do with limits on data-urls in different browsers, for example 2MB in Chrome.
http://stackoverflow.com/a/6167680.

As a workaround you can use the raw data option.

**Comment by konklone** [comment]
OK, so then the real issue here is I should mention somewhere that browsers have natural download limits. I renamed the issue to reflect that.
