### ISSUE TITLE
Error parsing some specific JSON

### ISSUE THREAD

**Issue by srikch** [konklone/json#124]
I'm having an issue converting this JSON:

I Have chrome extension, JSONView  0.0.32.3 
which provides Validate and view JSON documents.

once the json response is received on the browser this extension will format the json into readable format. 

{
status: 0,
 + data: []
}

where on clicking on + will expand the available data. 

when i copy paste into some text file the entire data is properly copied, 

now when i copy this data which is already formatted, there is a parsing error seen 

but if i copy it without this extension formatting the json, json to csv converter itself will format first and then parses properly. 

Hence third party formatted file is failing to parse.

**Comment by shivakaushal** [comment]
@srikch It might be due to invalid character encoding. The plugin might add text/spaces that could be making the JSON invalid.

**Comment by konklone** [comment]
JSONView for Chrome doesn't give valid JSON when copy/pasted. I recommend JSONFormatter for Chrome, or JSONView for Firefox.
