### ISSUE TITLE
Big data

### ISSUE THREAD

**Issue by Bharat-Verma** [konklone/json#126]
Hey,
I have 1gb file in JSON, which I wanna convert to csv. But because of browser limits I cant do it. Can you help me with that. Do you have some kind of python script that will help me.

Data can be found in the below link:

http://files.pushshift.io/reddit/requests/Reddit_Election_Raw_Data.zip

Please help.

**Comment by konklone** [comment]
Hi @Bharat-Verma -- I would take a look at `csvkit`'s `in2csv` module:

http://csvkit.readthedocs.io/en/1.0.1/scripts/in2csv.html

It doesn't recursively flatten JSON like this tool does, but it may be helpful to you.
