### ISSUE TITLE
regarding many data file

### ISSUE THREAD

**Issue by buddish** [konklone/json#129]
Hi, this is Jaeho. 

I am currently have a over 2500 rows of json type data in txt file format. 

I found out when I copy and paste them into the window, the conversion stops.. 

is there a way that I could get the nice table with the data?

the issue I have now is.. I have about 50 more files like that so..

Could you please let me know how can I convert them as the table? 

Thank you!!

Sincerely,
Jaeho

**Comment by konklone** [comment]
That's a little too broadly described, but it sounds like you may not have a single JSON object, but many small JSON objects. We don't support that sort of conversion, and aren't likely to. But if you want to paste a sample of two "rows" of what you're converting, I can 👁 it.
