### ISSUE TITLE
Streaming JSON parser?

### ISSUE THREAD

**Issue by konklone** [konklone/json#13]
If it's coming from a URL, can we do streaming JSON in-browser? @maxogden [sez](https://github.com/okfn/datapipes/issues/16#issuecomment-28649865):

> JSONStream is good but not perfect (has memory leaks iirc). More recently there's a library called oboe.js that looks good but I haven't tried it yet.

Oboe.js [is here](http://oboejs.com/) and it certainly _projects_ maturity.

**Comment by konklone** [comment]
Of course, even if the streaming makes the parsing of large files quicker, streaming the output may be more tricky. I don't believe you can do client-side streaming downloads via data URIs, for instance.

So the result will probably just be in memory. We can at least only display a header excerpt for the rendered version of large output, and not allow a total raw view (only a download link).

**Comment by max-mapper** [comment]
Yea, xhr isn't actually streaming today in
Browsers. You can fake it by making multiple requests to a server that
respects range requests or you can use websockets. You can also fake
streaming with the file reader API for local files (drag and drop etc)

**Comment by konklone** [comment]
Sounds not worth it, then, at least until the [Streams API](https://dvcs.w3.org/hg/streams-api/raw-file/tip/Overview.htm) makes it farther along.
