### ISSUE TITLE
Download the entire CSV - Nothing happens

### ISSUE THREAD

**Issue by aescobar100** [konklone/json#132]
After successfully parsing a download from https://labs.data.gov/dashboard/datagov/convert?orgs=dot-gov, I hit the Download the entire CSV file and nothing happens.

**Comment by konklone** [comment]
You downloaded the 1MB+ JSON From that URL and then tried converting it?

It looks like the server gives an HTML error message just before outputting the JSON:

```
<div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">

<h4>A PHP Error was encountered</h4>

<p>Severity: Warning</p>
<p>Message:  Invalid argument supplied for foreach()</p>
<p>Filename: models/campaign_model.php</p>
<p>Line Number: 2292</p>

</div>[
    {
        "issued": "2000-01-01T00:00:00-0500",
        "theme": [
            "Transportation"
        ],
        "license": "https:\/\/p...
```

By removing the error HTML, I was able to get it to work -- here's the permalink: 

https://konklone.io/json/?id=de8393c8a41b713dad48139a715c14a3

I'm closing this as not-a-bug in this repo, but cc-ing @philipashlock from the Data.gov team so he sees the actual server error.

**Comment by aescobar100** [comment]
Thanks!
