### ISSUE TITLE
Error parsing some specific JSON

### ISSUE THREAD

**Issue by prajwalMR** [konklone/json#140]
I'm having an issue converting this JSON:

```json
https://envirocar.org/api/stable/tracks/58c24888268d1b08d804f99a

I validated the JSON in http://jsonlint.com/ and it says it is a valid JSON.

Could anyone help me figure out, why this JSON is not being able to be processed?
```

**Comment by konklone** [comment]
Did you copy the contents of the JSON? It looks like you might have pasted in the URL to the JSON and not the JSON itself.

I pasted the contents of https://envirocar.org/api/stable/tracks/58c24888268d1b08d804f99a into the converter and it worked well. Here's a permalink:

https://konklone.io/json/?id=d95e99c004af5338751551ea2db17b6e
