### ISSUE TITLE
Error parsing some specific JSON

### ISSUE THREAD

**Issue by samequefarias** [konklone/json#145]
I'm having an issue converting this JSON:

{
  "created_at": "Mon Apr 17 13:01:10 +0000 2017",
  "id": 853956503224676353,
  "id_str": "853956503224676353",
  "text": "Oeee bom dia galera",
  "truncated": false,
  "entities": {
    "hashtags": [],
    "symbols": [],
    "user_mentions": [],
    "urls": []
  },
  "metadata": {
    "iso_language_code": "pt",
    "result_type": "recent"
  },
  "source": "<a href=\"http://twitter.com/download/iphone\" rel=\"nofollow\">Twitter for iPhone</a>",
  "in_reply_to_status_id": null,
  "in_reply_to_status_id_str": null,
  "in_reply_to_user_id": null,
  "in_reply_to_user_id_str": null,
  "in_reply_to_screen_name": null,
  "user": {
    "id": 411960656,
    "id_str": "411960656",
    "name": "Sameque Farias",
    "screen_name": "samequefarias",
    "location": "Fortaleza, Cear\u00e1",
    "description": "Mestre em Sistemas de Comunica\u00e7\u00e3o e Automa\u00e7\u00e3o e Doutorando em Engenharia de transportes.",
    "url": "https://t.co/taMBsDa9tr",
    "entities": {
      "url": {
        "urls": [
          {
            "url": "https://t.co/taMBsDa9tr",
            "expanded_url": "https://instagram.com/samequefarias/",
            "display_url": "instagram.com/samequefarias/",
            "indices": [
              0,
              23
            ]
          }
        ]
      },
      "description": {
        "urls": []
      }
    },
    "protected": false,
    "followers_count": 455,
    "friends_count": 1119,
    "listed_count": 1,
    "created_at": "Mon Nov 14 03:09:45 +0000 2011",
    "favourites_count": 18,
    "utc_offset": -10800,
    "time_zone": "Brasilia",
    "geo_enabled": true,
    "verified": false,
    "statuses_count": 1507,
    "lang": "pt",
    "contributors_enabled": false,
    "is_translator": false,
    "is_translation_enabled": false,
    "profile_background_color": "9AE4E8",
    "profile_background_image_url": "http://abs.twimg.com/images/themes/theme16/bg.gif",
    "profile_background_image_url_https": "https://abs.twimg.com/images/themes/theme16/bg.gif",
    "profile_background_tile": false,
    "profile_image_url": "http://pbs.twimg.com/profile_images/744540867977973760/kfYTJqcf_normal.jpg",
    "profile_image_url_https": "https://pbs.twimg.com/profile_images/744540867977973760/kfYTJqcf_normal.jpg",
    "profile_banner_url": "https://pbs.twimg.com/profile_banners/411960656/1441744776",
    "profile_link_color": "121F24",
    "profile_sidebar_border_color": "FFFFFF",
    "profile_sidebar_fill_color": "99CC33",
    "profile_text_color": "3E4415",
    "profile_use_background_image": true,
    "has_extended_profile": false,
    "default_profile": false,
    "default_profile_image": false,
    "following": null,
    "follow_request_sent": null,
    "notifications": null,
    "translator_type": "none"
  },
  "geo": null,
  "coordinates": null,
  "place": {
    "id": "07d9d2acbdc85001",
    "url": "https://api.twitter.com/1.1/geo/id/07d9d2acbdc85001.json",
    "place_type": "poi",
    "name": "Universidade Federal do Cear\u00e1 (Campus do Pici)",
    "full_name": "Universidade Federal do Cear\u00e1 (Campus do Pici)",
    "country_code": "BR",
    "country": "Brazil",
    "contained_within": [],
    "bounding_box": {
      "type": "Polygon",
      "coordinates": [
        [
          [
            -38.575358390808105,
            -3.7437569222834437
          ],
          [
            -38.575358390808105,
            -3.7437569222834437
          ],
          [
            -38.575358390808105,
            -3.7437569222834437
          ],
          [
            -38.575358390808105,
            -3.7437569222834437
          ]
        ]
      ]
    },
    "attributes": {}
  },
  "contributors": null,
  "is_quote_status": false,
  "retweet_count": 0,
  "favorite_count": 0,
  "favorited": false,
  "retweeted": false,
  "lang": "pt"
}

runfile('C:/Users/Dell casa/Desktop/Teste 4 dias dias da semana/UdG-seminar-master/temp.py', wdir='C:/Users/Dell casa/Desktop/Teste 4 dias dias da semana/UdG-seminar-master')
{
  "created_at": "Mon Apr 17 13:01:10 +0000 2017",
  "id": 853956503224676353,
  "id_str": "853956503224676353",
  "text": "Oeee bom dia galera",
  "truncated": false,
  "entities": {
    "hashtags": [],
    "symbols": [],
    "user_mentions": [],
    "urls": []
  },
  "metadata": {
    "iso_language_code": "pt",
    "result_type": "recent"
  },
  "source": "<a href=\"http://twitter.com/download/iphone\" rel=\"nofollow\">Twitter for iPhone</a>",
  "in_reply_to_status_id": null,
  "in_reply_to_status_id_str": null,
  "in_reply_to_user_id": null,
  "in_reply_to_user_id_str": null,
  "in_reply_to_screen_name": null,
  "user": {
    "id": 411960656,
    "id_str": "411960656",
    "name": "Sameque Farias",
    "screen_name": "samequefarias",
    "location": "Fortaleza, Cear\u00e1",
    "description": "Mestre em Sistemas de Comunica\u00e7\u00e3o e Automa\u00e7\u00e3o e Doutorando em Engenharia de transportes.",
    "url": "https://t.co/taMBsDa9tr",
    "entities": {
      "url": {
        "urls": [
          {
            "url": "https://t.co/taMBsDa9tr",
            "expanded_url": "https://instagram.com/samequefarias/",
            "display_url": "instagram.com/samequefarias/",
            "indices": [
              0,
              23
            ]
          }
        ]
      },
      "description": {
        "urls": []
      }
    },
    "protected": false,
    "followers_count": 455,
    "friends_count": 1119,
    "listed_count": 1,
    "created_at": "Mon Nov 14 03:09:45 +0000 2011",
    "favourites_count": 18,
    "utc_offset": -10800,
    "time_zone": "Brasilia",
    "geo_enabled": true,
    "verified": false,
    "statuses_count": 1507,
    "lang": "pt",
    "contributors_enabled": false,
    "is_translator": false,
    "is_translation_enabled": false,
    "profile_background_color": "9AE4E8",
    "profile_background_image_url": "http://abs.twimg.com/images/themes/theme16/bg.gif",
    "profile_background_image_url_https": "https://abs.twimg.com/images/themes/theme16/bg.gif",
    "profile_background_tile": false,
    "profile_image_url": "http://pbs.twimg.com/profile_images/744540867977973760/kfYTJqcf_normal.jpg",
    "profile_image_url_https": "https://pbs.twimg.com/profile_images/744540867977973760/kfYTJqcf_normal.jpg",
    "profile_banner_url": "https://pbs.twimg.com/profile_banners/411960656/1441744776",
    "profile_link_color": "121F24",
    "profile_sidebar_border_color": "FFFFFF",
    "profile_sidebar_fill_color": "99CC33",
    "profile_text_color": "3E4415",
    "profile_use_background_image": true,
    "has_extended_profile": false,
    "default_profile": false,
    "default_profile_image": false,
    "following": null,
    "follow_request_sent": null,
    "notifications": null,
    "translator_type": "none"
  },
  "geo": null,
  "coordinates": null,
  "place": {
    "id": "07d9d2acbdc85001",
    "url": "https://api.twitter.com/1.1/geo/id/07d9d2acbdc85001.json",
    "place_type": "poi",
    "name": "Universidade Federal do Cear\u00e1 (Campus do Pici)",
    "full_name": "Universidade Federal do Cear\u00e1 (Campus do Pici)",
    "country_code": "BR",
    "country": "Brazil",
    "contained_within": [],
    "bounding_box": {
      "type": "Polygon",
      "coordinates": [
        [
          [
            -38.575358390808105,
            -3.7437569222834437
          ],
          [
            -38.575358390808105,
            -3.7437569222834437
          ],
          [
            -38.575358390808105,
            -3.7437569222834437
          ],
          [
            -38.575358390808105,
            -3.7437569222834437
          ]
        ]
      ]
    },
    "attributes": {}
  },
  "contributors": null,
  "is_quote_status": false,
  "retweet_count": 0,
  "favorite_count": 0,
  "favorited": false,
  "retweeted": false,
  "lang": "pt"
}

**Comment by konklone** [comment]
This isn't JSON. You've got this stuff in there:

```
runfile('C:/Users/Dell casa/Desktop/Teste 4 dias dias da semana/UdG-seminar-master/temp.py', wdir='C:/Users/Dell casa/Desktop/Teste 4 dias dias da semana/UdG-seminar-master')
```

And there are two different JSON objects, one above those lines and one below those lines.
