### ISSUE TITLE
Downloaded csv file is not in proper format

### ISSUE THREAD

**Issue by ShivanandKhobanna** [konklone/json#146]
when I past the json data in the json field, I can see a table( basically first few rows) which looks perfect. But when download the csv file, its not in the proper format.

**Comment by konklone** [comment]
@ShivanandKhobanna Could you provide a permalink to an example so I can reproduce the issue?

**Comment by ShivanandKhobanna** [comment]
Thanks a lot for quick reply :) please find below the requested permalink:
https://konklone.io/json/?id=1d55cf1209f8ce739ffe91172ef283ef

The sample table which i see is perfect, though it contains lot of blank rows.

**Comment by konklone** [comment]
Hmm, I can't reproduce this. I see a sample table that looks good, and when I download the CSV it looks just the same, and I don't see any blank rows.

Is it possible your spreadsheet viewer is using a delimiter other than a comma?
