### ISSUE TITLE
Error parsing some specific JSON

### ISSUE THREAD

**Issue by beyzaturan** [konklone/json#148]
I'm having an issue converting this JSON:

{
  "data": [
    {
      "destination_airport": "BKK",
      "id": "1722625807752677",
      "origin_airport": "AMS"
    },
    {
      "destination_airport": "CPT",
      "id": "1334780439936456",
      "origin_airport": "AMS"
    },
    {
      "destination_airport": "HRG",
      "id": "1266250090155006",
      "origin_airport": "AMS"
    },
    {
      "destination_airport": "KTM",
      "id": "1029454003822991",
      "origin_airport": "AMS"
    },
    {
      "destination_airport": "SEZ",
      "id": "1260907527359117",
      "origin_airport": "AMS"
    },
    {
      "destination_airport": "SSH",
      "id": "1374098402656071",
      "origin_airport": "AMS"
    },
    {
      "destination_airport": "BKK",
      "id": "1519840041389200",
      "origin_airport": "ATH"
    },
    {
      "destination_airport": "CMB",
      "id": "1510550442309166",
      "origin_airport": "ATH"
    },
    {
      "destination_airport": "CPT",
      "id": "1308102072637319",
      "origin_airport": "ATH"
    },
    {
      "destination_airport": "HAN",
      "id": "1357492887671166",
      "origin_airport": "ATH"
    },
    {
      "destination_airport": "HRG",
      "id": "1652742728073835",
      "origin_airport": "ATH"
    },
    {
      "destination_airport": "MNL",
      "id": "1455653807819198",
      "origin_airport": "ATH"
    },
    {
      "destination_airport": "NBO",
      "id": "1531146026968135",
      "origin_airport": "ATH"
    },
    {
      "destination_airport": "SEZ",
      "id": "1330524903669943",
      "origin_airport": "ATH"
    },
    {
      "destination_airport": "SSH",
      "id": "1709199542428336",
      "origin_airport": "ATH"
    },
    {
      "destination_airport": "TNR",
      "id": "1808814159189465",
      "origin_airport": "ATH"
    },
    {
      "destination_airport": "TPE",
      "id": "1658491270835352",
      "origin_airport": "ATH"
    },
    {
      "destination_airport": "BKK",
      "id": "1556879141021319",
      "origin_airport": "BCN"
    },
    {
      "destination_airport": "CMB",
      "id": "1020845251350630",
      "origin_airport": "BCN"
    },
    {
      "destination_airport": "CPT",
      "id": "1459517204121830",
      "origin_airport": "BCN"
    },
    {
      "destination_airport": "HAN",
      "id": "1587356447983182",
      "origin_airport": "BCN"
    },
    {
      "destination_airport": "HRG",
      "id": "1281960981920436",
      "origin_airport": "BCN"
    },
    {
      "destination_airport": "KTM",
      "id": "1663622456989213",
      "origin_airport": "BCN"
    },
    {
      "destination_airport": "MBA",
      "id": "1406937786042914",
      "origin_airport": "BCN"
    },
    {
      "destination_airport": "MNL",
      "id": "1319688064786731",
      "origin_airport": "BCN"
    },
    {
      "destination_airport": "NBO",
      "id": "1650448031650962",
      "origin_airport": "BCN"
    },
    {
      "destination_airport": "SEZ",
      "id": "1505439799488044",
      "origin_airport": "BCN"
    },
    {
      "destination_airport": "SSH",
      "id": "1526838643993395",
      "origin_airport": "BCN"
    },
    {
      "destination_airport": "TNR",
      "id": "1468545863218125",
      "origin_airport": "BCN"
    },
    {
      "destination_airport": "TPE",
      "id": "1373984689349931",
      "origin_airport": "BCN"
    },
    {
      "destination_airport": "BKK",
      "id": "1261541777227244",
      "origin_airport": "BRU"
    },
    {
      "destination_airport": "CMB",
      "id": "1066727010093958",
      "origin_airport": "BRU"
    },
    {
      "destination_airport": "CPT",
      "id": "1499040416781152",
      "origin_airport": "BRU"
    },
    {
      "destination_airport": "HAN",
      "id": "1364412140275122",
      "origin_airport": "BRU"
    },
    {
      "destination_airport": "HRG",
      "id": "1619437858096381",
      "origin_airport": "BRU"
    },
    {
      "destination_airport": "KTM",
      "id": "1309506935810605",
      "origin_airport": "BRU"
    },
    {
      "destination_airport": "MBA",
      "id": "1264663070236426",
      "origin_airport": "BRU"
    },
    {
      "destination_airport": "MNL",
      "id": "1321895547895916",
      "origin_airport": "BRU"
    },
    {
      "destination_airport": "NBO",
      "id": "1330111730399420",
      "origin_airport": "BRU"
    },
    {
      "destination_airport": "SEZ",
      "id": "1582215115152337",
      "origin_airport": "BRU"
    },
    {
      "destination_airport": "SSH",
      "id": "1798060540207733",
      "origin_airport": "BRU"
    },
    {
      "destination_airport": "TPE",
      "id": "1375360515881593",
      "origin_airport": "BRU"
    },
    {
      "destination_airport": "BKK",
      "id": "1730781220299668",
      "origin_airport": "CDG"
    },
    {
      "destination_airport": "CMB",
      "id": "1647694068592064",
      "origin_airport": "CDG"
    },
    {
      "destination_airport": "CPT",
      "id": "1322860294464610",
      "origin_airport": "CDG"
    },
    {
      "destination_airport": "HAN",
      "id": "1051313618303654",
      "origin_airport": "CDG"
    },
    {
      "destination_airport": "KTM",
      "id": "1622446094462555",
      "origin_airport": "CDG"
    },
    {
      "destination_airport": "MBA",
      "id": "1631338446895393",
      "origin_airport": "CDG"
    },
    {
      "destination_airport": "MNL",
      "id": "1191908090931299",
      "origin_airport": "CDG"
    },
    {
      "destination_airport": "NBO",
      "id": "1271081309613765",
      "origin_airport": "CDG"
    },
    {
      "destination_airport": "SEZ",
      "id": "1725680914114883",
      "origin_airport": "CDG"
    },
    {
      "destination_airport": "TNR",
      "id": "1522297691137974",
      "origin_airport": "CDG"
    },
    {
      "destination_airport": "TPE",
      "id": "1307931885968730",
      "origin_airport": "CDG"
    },
    {
      "destination_airport": "BKK",
      "id": "1254623711254142",
      "origin_airport": "CPH"
    },
    {
      "destination_airport": "CMB",
      "id": "1286105551505552",
      "origin_airport": "CPH"
    },
    {
      "destination_airport": "CPT",
      "id": "1845407895485216",
      "origin_airport": "CPH"
    },
    {
      "destination_airport": "KTM",
      "id": "1342940662458629",
      "origin_airport": "CPH"
    },
    {
      "destination_airport": "MNL",
      "id": "1456570851059675",
      "origin_airport": "CPH"
    },
    {
      "destination_airport": "NBO",
      "id": "1275116249268901",
      "origin_airport": "CPH"
    },
    {
      "destination_airport": "TPE",
      "id": "1333638483392883",
      "origin_airport": "CPH"
    },
    {
      "destination_airport": "BKK",
      "id": "1396256293764238",
      "origin_airport": "DUB"
    },
    {
      "destination_airport": "CMB",
      "id": "1549316901779262",
      "origin_airport": "DUB"
    },
    {
      "destination_airport": "CPT",
      "id": "1328712250546539",
      "origin_airport": "DUB"
    },
    {
      "destination_airport": "HAN",
      "id": "1382953668429483",
      "origin_airport": "DUB"
    },
    {
      "destination_airport": "HRG",
      "id": "1502250389850101",
      "origin_airport": "DUB"
    },
    {
      "destination_airport": "MBA",
      "id": "1181013018688651",
      "origin_airport": "DUB"
    },
    {
      "destination_airport": "MNL",
      "id": "1464403890268278",
      "origin_airport": "DUB"
    },
    {
      "destination_airport": "NBO",
      "id": "1514780965220759",
      "origin_airport": "DUB"
    },
    {
      "destination_airport": "SEZ",
      "id": "1634602276568866",
      "origin_airport": "DUB"
    },
    {
      "destination_airport": "SSH",
      "id": "1498618243481632",
      "origin_airport": "DUB"
    },
    {
      "destination_airport": "TPE",
      "id": "1257170887671495",
      "origin_airport": "DUB"
    },
    {
      "destination_airport": "BKK",
      "id": "1811073698906540",
      "origin_airport": "HEL"
    },
    {
      "destination_airport": "CMB",
      "id": "1320722974663890",
      "origin_airport": "HEL"
    },
    {
      "destination_airport": "CPT",
      "id": "1549881978397036",
      "origin_airport": "HEL"
    },
    {
      "destination_airport": "HAN",
      "id": "1481061115300064",
      "origin_airport": "HEL"
    },
    {
      "destination_airport": "HRG",
      "id": "1296681267076093",
      "origin_airport": "HEL"
    },
    {
      "destination_airport": "KTM",
      "id": "1352649111470233",
      "origin_airport": "HEL"
    },
    {
      "destination_airport": "MBA",
      "id": "1426901524051249",
      "origin_airport": "HEL"
    },
    {
      "destination_airport": "MNL",
      "id": "1350906041622987",
      "origin_airport": "HEL"
    },
    {
      "destination_airport": "NBO",
      "id": "1418629471530665",
      "origin_airport": "HEL"
    },
    {
      "destination_airport": "SEZ",
      "id": "1338142082959654",
      "origin_airport": "HEL"
    },
    {
      "destination_airport": "SSH",
      "id": "1524533337620497",
      "origin_airport": "HEL"
    },
    {
      "destination_airport": "TNR",
      "id": "1261343260651410",
      "origin_airport": "HEL"
    },
    {
      "destination_airport": "TPE",
      "id": "1318783321531533",
      "origin_airport": "HEL"
    },
    {
      "destination_airport": "BKK",
      "id": "1232444886854358",
      "origin_airport": "OSL"
    },
    {
      "destination_airport": "CMB",
      "id": "1509696249064430",
      "origin_airport": "OSL"
    },
    {
      "destination_airport": "CPT",
      "id": "1076058455828977",
      "origin_airport": "OSL"
    },
    {
      "destination_airport": "HAN",
      "id": "1419985711355049",
      "origin_airport": "OSL"
    },
    {
      "destination_airport": "HRG",
      "id": "1464256303648616",
      "origin_airport": "OSL"
    },
    {
      "destination_airport": "KTM",
      "id": "1290891151029991",
      "origin_airport": "OSL"
    },
    {
      "destination_airport": "MBA",
      "id": "1160039807452145",
      "origin_airport": "OSL"
    },
    {
      "destination_airport": "MNL",
      "id": "1620845031289684",
      "origin_airport": "OSL"
    },
    {
      "destination_airport": "NBO",
      "id": "1353989848027769",
      "origin_airport": "OSL"
    },
    {
      "destination_airport": "SEZ",
      "id": "1434648893222905",
      "origin_airport": "OSL"
    },
    {
      "destination_airport": "SSH",
      "id": "1514714545214715",
      "origin_airport": "OSL"
    },
    {
      "destination_airport": "TNR",
      "id": "1300395566676388",
      "origin_airport": "OSL"
    },
    {
      "destination_airport": "TPE",
      "id": "1184899418299505",
      "origin_airport": "OSL"
    },
    {
      "destination_airport": "BKK",
      "id": "1320685328009587",
      "origin_airport": "VKO"
    },
    {
      "destination_airport": "CMB",
      "id": "1494571143918296",
      "origin_airport": "VKO"
    },
    {
      "destination_airport": "CPT",
      "id": "1315560368531166",
      "origin_airport": "VKO"
    },
    {
      "destination_airport": "HAN",
      "id": "1286270071471938",
      "origin_airport": "VKO"
    },
    {
      "destination_airport": "HRG",
      "id": "1507187992656792",
      "origin_airport": "VKO"
    },
    {
      "destination_airport": "KTM",
      "id": "1520802014658855",
      "origin_airport": "VKO"
    },
    {
      "destination_airport": "MBA",
      "id": "1739786009369864",
      "origin_airport": "VKO"
    },
    {
      "destination_airport": "MNL",
      "id": "1304423392957372",
      "origin_airport": "VKO"
    },
    {
      "destination_airport": "NBO",
      "id": "1205995622856888",
      "origin_airport": "VKO"
    },
    {
      "destination_airport": "SEZ",
      "id": "1404777992877973",
      "origin_airport": "VKO"
    },
    {
      "destination_airport": "SSH",
      "id": "1251365748310124",
      "origin_airport": "VKO"
    },
    {
      "destination_airport": "TNR",
      "id": "1402220269870855",
      "origin_airport": "VKO"
    },
    {
      "destination_airport": "TPE",
      "id": "1239912132793193",
      "origin_airport": "VKO"
    },
    {
      "destination_airport": "BKK",
      "id": "1528447210530776",
      "origin_airport": "ZRH"
    },
    {
      "destination_airport": "CPT",
      "id": "1425347810872656",
      "origin_airport": "ZRH"
    },
    {
      "destination_airport": "HAN",
      "id": "1399123000145742",
      "origin_airport": "ZRH"
    },
    {
      "destination_airport": "HRG",
      "id": "1664523383576315",
      "origin_airport": "ZRH"
    },
    {
      "destination_airport": "KTM",
      "id": "1465414580182997",
      "origin_airport": "ZRH"
    },
    {
      "destination_airport": "MBA",
      "id": "1321743571248924",
      "origin_airport": "ZRH"
    },
    {
      "destination_airport": "MNL",
      "id": "1478312662239860",
      "origin_airport": "ZRH"
    },
    {
      "destination_airport": "NBO",
      "id": "1513501285327972",
      "origin_airport": "ZRH"
    },
    {
      "destination_airport": "SSH",
      "id": "1447365298619365",
      "origin_airport": "ZRH"
    }
  ]

**Comment by konklone** [comment]
Looks like you're missing a brace `}` at the end. The JSON starts with a `{`, but ends with a `]`.
