### ISSUE TITLE
XSS because HTML is not encoded

### ISSUE THREAD

**Issue by macintorsten** [konklone/json#163]
The JSON to CSV tool allows one to enter HTML code that will not be escaped. The 'Create permalink' can be used to a link with arbitrary code to another person, so it's no longer just self-xss.

1. Go to https://konklone.io/json/
2. Enter text `{"xss": "<div onclick=alert(document.domain)>Click me</div>"}`
   
   `{"xss": "<iframe src=javascript:alert(document.domain)>"}` is another option that requires no click.
3. Click on the text 'Click me'

This will pop up a javascript alert box.

**Comment by konklone** [comment]
Thank you very much for fixing this in #164!
