### ISSUE TITLE
Support for Norwegian characters

### ISSUE THREAD

**Issue by furier** [konklone/json#165]
Currently the Norwegian characters are not converted correctly in the output file.

**Comment by konklone** [comment]
Could you create a permalink and show me an example?

**Comment by furier** [comment]
Hmmm if the file is opened in excel directly the characters are shown weird, but in notepad they are fine. However if I copy paste the content from notepad into excel everything is good.

https://konklone.io/json/?id=2b6b0da308b0345e8dadf5b07c5e96bf

**Comment by konklone** [comment]
Yeah, I see what you mean (and I can reproduce in Excel). So, this sounds like an Excel issue.
