### ISSUE TITLE
Increase HTML table rows limit

### ISSUE THREAD

**Issue by nevcos** [konklone/json#166]
This tool is great to view and share JSON lists in a simple way, but limiting the table to only 7 rows is very restrictive.

Please consider increasing the limit to about 200 rows, so that the HTML table can be used in most of the cases without the need to export to CSV.

**Comment by konklone** [comment]
The HTML tables can be quite large, even with 7 rows, depending how the data is structured. I could try to have a sophisticated heuristic that chooses the row number based on column count of the first row, but that seems a bit complex for what this is.

In general, the HTML table is really just meant to be a preview and sanity check. It's not meant to be a first class data viewer. I haven't heard of folks using it as the end product before, and I didn't design it to be used that way.

**Comment by nevcos** [comment]
Hi @konklone, 

As developer multiple times I need to use tools like ``json2table.com``, ``konklone.io/json`` and ``console.table`` to debug JSON data in a better/faster way.

If ``json2table.com`` works OK for "non-shareable" data, ``konklone.io/json`` permalink/gist feature is really awesome to share the same data/view with the rest of the team (and including it in documents and Jira issues).

For this reason, I think your project can not only serve those users that really prefer the CSV format (not my case because it's slower to get and format the results in a good way using Excel) like users like me that just want a quick way of seeing the list in a HTML table and share it with other people (you probably can have an idea of the amount of users like me checking the analytics on the CSV export feature vs page views).

About performance, you can consider continue showing a preview and adding a new "show all" button (so that users only wanting to export data will not be affected).

Thanks

**Comment by konklone** [comment]
@nevcos OK, I think a `Show all` link of some kind would be welcome, for those who want to use it that way. Do you care enough to file a pull request to add the code for it? Don't worry too much about the UI, I can adjust how/where the link would show up.

**Comment by nevcos** [comment]
@konklone Sure! Will work on that next week.
Thanks!

**Comment by nevcos** [comment]
@konklone Created a PR, please check if everything is OK.
Thanks!

**Comment by konklone** [comment]
This was fixed by #168.
