### ISSUE TITLE
Error parsing some specific JSON

### ISSUE THREAD

**Issue by kdrglmz** [konklone/json#170]
I'm having an issue converting this JSON:

```json
[{'Name':'Kadir','Surname':'GÜLMEZ'},{'Name':'Önder','Surname':'LOP'},{'Name':'Sadık','Surname':'SARIBAŞ'},{'Name':'Bülent','Surname':'SÖNMEZ'},{'Name':'Burak','Surname':'burak'}];

```

**Comment by konklone** [comment]
It's the single quotes, and also possible the semicolon at the end. If you switch the single quotes to double quotes, and remove the semicolon, it should work.
