### ISSUE TITLE
Download the entire CSV does not work

### ISSUE THREAD

**Issue by shayc1** [konklone/json#171]
I use this site once a week. It's excellent. Last week the Download worked. Today it doesn't.

**Comment by konklone** [comment]
@shayc1 I did make a change 4 days ago to address #168, so there could be an impact. 

But, I just went and tested out the download feature with some public data (https://konklone.io/json/?id=f9267d03c30fe91a02cbce226b6c40ce) and it works fine for me.

Can you provide me a permalink to some data where the download feature is not working?

**Comment by shayc1** [comment]
Sorry, my mistake. It just took some time but finally it worked.

2017-07-19 22:40 GMT+03:00 Eric Mill <notifications@github.com>:
