### ISSUE TITLE
Error parsing some specific JSON

### ISSUE THREAD

**Issue by phuongngokhac** [konklone/json#174]
I'm having an issue converting this JSON:

https://konklone.io/json/?id=b70e275ddf11b5b7043d4570373b77dd

[redacted for containing an access token]

**Comment by konklone** [comment]
You pasted in a URL, rather than the JSON at the URL. The app doesn't fetch content at remote URLs. 

I'm also removing this content from the issue, as you've included an `access_token`. You should revoke and recycle this token in your Facebook settings.
