### ISSUE TITLE
All of a sudden not converting tables

### ISSUE THREAD

**Issue by kfunck1** [konklone/json#181]
Hi,

First thanks for the great tool. I had been using it for a few weeks to copy/paste some data off the ubereats website, and the tool would take it and break it out into the proper categories (restaurant name, latitude, longitude, etc, etc.) Now it seems it cannot and it only returns 3 values "Sort" "Price" and "Dietary," even though all of the data is still present. I have tried messing with it but to no avail. Any thoughts?

eta: all the data I need is in the "storesmap" array which is under marketplace/feed, for some reason it just won't parse that anymore.

https://konklone.io/json/?id=f77e53e613bb04cdfccbccab9ffb7c39#

**Comment by konklone** [comment]
@kfunck1 Sorry to take so long to respond, though I've looked at it a few times and I'm not sure what would have changed, besides Ubereats' own format. 

The converter tries to figure out what the "primary array" is that it should be using to decide what a "row" is, which is a best-effort kind of thing, and if it picks the wrong thing it can cut out some data entirely. It might even come down to indeterministic things like key order during JSON parsing. :/ There's not a simple one-to-one mapping of JSON to CSV. 

You might try cutting down the JSON to just the `marketplace.feed` sub-object, to make it less ambiguous to the parser, if that's all you want. I could imagine adding a feature to specify the field to look for "the array" in, though that would still require understanding the structure of the JSON a little bit on the user's part.
