### ISSUE TITLE
Getting the download failed - network error

### ISSUE THREAD

**Issue by plsr2513** [konklone/json#199]
I have a 9MB json file I'm trying to convert to a csv.  When I try to download the csv it fails.

**Comment by konklone** [comment]
@plsr2513 What browser/OS are you using? Some browsers impose smaller limits in what data can be assembled for direct download, which I can't do anything about.

Try a few browsers and see if that changes things.

**Comment by fernandohg97** [comment]
I tried with Microsoft Edge and it doesn't work. But with Google Chrome and Firefox works well.

**Comment by konklone** [comment]
Got it - yeah, that's known, and nothing I can do about it. However, I added a note to the site in https://github.com/konklone/json/commit/50dc9bfd539707cdec68c198a7c9fba03cb068f5 that notes that Edge has a lower limit than other browsers.
