### ISSUE TITLE
Permalink feature not working.

### ISSUE THREAD

**Issue by Jfairfield1** [konklone/json#205]
When I click the "Create a permalink" link, nothing happens and when I go into the developer console, I notice an error:

![image](https://user-images.githubusercontent.com/13153086/37678318-eef90d8c-2c3a-11e8-9791-4df34230a433.png)

> documentation_url:"https://developer.github.com/v3/gists/#create-a-gist" errors :[{resource: "Gist", code: "missing_field", field: "user"}] 0 :{resource: "Gist", code: "missing_field", field: "user"} code :"missing_field" field :"user" resource :"Gist" message :"Validation Failed"  

I wonder if anonymous Gist's are still allowed by github?

Here is some wording from their api documentation:

> You can read public gists and create them for anonymous users without a token; however, to read or write gists on a user's behalf the gist OAuth scope is required.

**Comment by konklone** [comment]
Hmm, you are right, this is not working anymore. I'll have to look into it, thanks for letting me know.

**Comment by ry4nolson** [comment]
it errors with a `401 Unauthorized` now.

```json
{
  "message": "Requires authentication",
  "documentation_url": "https://developer.github.com/v3/gists/#create-a-gist"
}
```

**Comment by konklone** [comment]
This feature has been removed, since GitHub removed support for anonymous gists via API.
