### ISSUE TITLE
Large numbers don't work well for CSV file download

### ISSUE THREAD

**Issue by bworsfold** [konklone/json#213]
Large numbers seem to get truncated in the generated csv that is downloadable.  The in browser version works just fine.

![image](https://user-images.githubusercontent.com/4193478/39337225-a3d8a058-4970-11e8-8804-85f2c1cfe46d.png)

![image](https://user-images.githubusercontent.com/4193478/39337243-c2695a80-4970-11e8-81e9-4131b48f78b5.png)

Sample number to use in json: 10000000000004326357

**Comment by bworsfold** [comment]
Here is a good simple json payload to work with:
{"foo":"10000000000004326357"}

**Comment by javadev** [comment]
Looks like it was fixed.

**Comment by konklone** [comment]
I'm reasonably sure this is/was an Excel issue, not an issue with how the CSV was generated. Let me know if that's not the case.
