### ISSUE TITLE
Error parsing some specific JSON

### ISSUE THREAD

**Issue by Hanhanziyi** [konklone/json#216]
I'm having an issue converting this JSON:
{"学者姓名": "陈志刚", "被访人数": "12299人看过", "scholarID": "CN-B174AKRJ", "工作单位": "中南大学信息科学与工程学院", "被引频次": "11100", "成果数": "1031", "H指数": "50", "G指数": "83", "研究领域": "通信与信息系统"}{"学者姓名": "胡志刚", "被访人数": "3548人看过", "scholarID": "CN-BK74YR2J", "工作单位": "中南大学信息科学与工程学院", "被引频次": "1717", "成果数": "301", "H指数": "20", "G指数": "29", "研究领域": "算法理论"}{"学者姓名": "赵明", "被访人数": "612人看过", "scholarID": "CN-BG75M7WJ", "工作单位": "中南大学信息科学与工程学院", "被引频次": "412", "成果数": "100", "H指数": "12", "G指数": "15", "研究领域": "通信与信息系统"}{"学者姓名": "曾锋", "被访人数": "250人看过", "scholarID": "CN-BI74308J", "工作单位": "中南大学信息科学与工程学院", "被引频次": "131", "成果数": "33", "H指数": "6", "G指数": "9", "研究领域": "通信与信息系统"}{"学者姓名": "郑美光", "被访人数": "46人看过", "scholarID": "CN-BA75B4OJ", "工作单位": "中南大学信息科学与工程学院", "被引频次": "8", "成果数": "17", "H指数": "2", "G指数": "2", "研究领域": "科学计算/自然语言处理/教育学"}{"学者姓名": "刘莉平", "被访人数": "325人看过", "scholarID": "CN-B974QMIJ", "工作单位": "中南大学软件学院", "被引频次": "146", "成果数": "39", "H指数": "6", "G指数": "10", "研究领域": "通信与信息系统"}{"学者姓名": "任胜兵", "被访人数": "870人看过", "scholarID": "CN-B27333ZJ", "工作单位": "中南大学信息科学与工程学院", "被引频次": "541", "成果数": "64", "H指数": "13", "G指数": "22", "研究领域": "软件工程"}{"学者姓名": "廖志芳", "被访人数": "565人看过", "scholarID": "CN-BD734CEJ", "工作单位": "中南大学软件学院", "被引频次": "318", "成果数": "109", "H指数": "9", "G指数": "14", "研究领域": "算法理论"}{"学者姓名": "谭长庚", "被访人数": "436人看过", "scholarID": "CN-BO74MBYJ", "工作单位": "中南大学信息科学与工程学院", "被引频次": "237", "成果数": "37", "H指数": "9", "G指数": "14", "研究领域": "计算机网络"}{"学者姓名": "费洪晓", "被访人数": "1964人看过", "scholarID": "CN-BX741NCJ", "工作单位": "中南大学信息科学与工程学院", "被引频次": "947", "成果数": "108", "H指数": "15", "G指数": "26", "研究领域": "计算机网络"}{"学者姓名": "陈学工", "被访人数": "994人看过", "scholarID": "CN-BF74J5CJ", "工作单位": "中南大学信息科学与工程学院", "被引频次": "574", "成果数": "72", "H指数": "13", "G指数": "21", "研究领域": "算法理论"}{"学者姓名": "郁松", "被访人数": "141人看过", "scholarID": "CN-B074JBKJ", "工作单位": "中南大学软件学院", "被引频次": "9", "成果数": "11", "H指数": "2", "G指数": "2", "研究领域": "算法理论"}{"学者姓名": "邝砾", "被访人数": "804人看过", "scholarID": "CN-BE74KQVJ", "工作单位": "浙江大学计算机科学与技术学院", "被引频次": "735", "成果数": "55", "H指数": "17", "G指数": "25", "研究领域": "操作系统"}{"学者姓名": "王一军", "被访人数": "303人看过", "scholarID": "CN-BA74H3MJ", "工作单位": "中南大学信息科学与工程学院", "被引频次": "146", "成果数": "51", "H指数": "6", "G指数": "10", "研究领域": "算法理论"}{"学者姓名": "杨柳", "被访人数": "689人看过", "scholarID": "CN-BU74XEXJ", "工作单位": "中南大学软件学院", "被引频次": "397", "成果数": "31", "H指数": "7", "G指数": "19", "研究领域": "软件工程"}{"学者姓名": "刘佳琦", "被访人数": "250人看过", "scholarID": "CN-B374LJFJ", "工作单位": "中南大学信息科学与工程学院", "被引频次": "146", "成果数": "35", "H指数": "6", "G指数": "10", "研究领域": "通信与信息系统"}{"学者姓名": "陈再良", "被访人数": "380人看过", "scholarID": "CN-B87441CJ", "工作单位": "中南大学信息科学与工程学院", "被引频次": "201", "成果数": "49", "H指数": "8", "G指数": "12", "研究领域": "算法理论"}{"学者姓名": "戴培山", "被访人数": "160人看过", "scholarID": "CN-BQ74IRJJ", "工作单位": "中南大学信息物理工程学院", "被引频次": "16", "成果数": "16", "H指数": "3", "G指数": "3", "研究领域": "生物科学与工程"}{"学者姓名": "冯启龙", "被访人数": "710人看过", "scholarID": "CN-B273Y06J", "工作单位": "中南大学信息科学与工程学院", "被引频次": "621", "成果数": "106", "H指数": "13", "G指数": "19", "研究领域": "算法理论/信息安全"}{"学者姓名": "桂劲松", "被访人数": "175人看过", "scholarID": "CN-B973QZVJ", "工作单位": "中南大学信息科学与工程学院", "被引频次": "95", "成果数": "31", "H指数": "6", "G指数": "8", "研究领域": "算法理论"}{"学者姓名": "郭克华", "被访人数": "173人看过", "scholarID": "CN-B873XHLJ", "工作单位": "南京理工大学计算机科学与技术学院", "被引频次": "94", "成果数": "40", "H指数": "5", "G指数": "7", "研究领域": "计算机视觉"}{"学者姓名": "黄东军", "被访人数": "1096人看过", "scholarID": "CN-B874BU9J", "工作单位": "中南大学信息科学与工程学院", "被引频次": "459", "成果数": "87", "H指数": "9", "G指数": "16", "研究领域": "算法理论"}{"学者姓名": "黄芳", "被访人数": "457人看过", "scholarID": "CN-BW75TJKJ", "工作单位": "中南大学信息科学与工程学院", "被引频次": "184", "成果数": "46", "H指数": "7", "G指数": "12", "研究领域": "算法理论"}{"学者姓名": "金瓯", "被访人数": "622人看过", "scholarID": "CN-BR74YO4J", "工作单位": "中南大学信息科学与工程学院", "被引频次": "289", "成果数": "66", "H指数": "10", "G指数": "14", "研究领域": "嵌入式系统"}{"学者姓名": "雷向东", "被访人数": "317人看过", "scholarID": "CN-BD75IL5J", "工作单位": "中南大学信息科学与工程学院", "被引频次": "186", "成果数": "49", "H指数": "7", "G指数": "11", "研究领域": "数据库"}{"学者姓名": "廖胜辉", "被访人数": "30人看过", "scholarID": "CN-BA730QNJ", "工作单位": "中南大学信息科学与工程学院", "被引频次": "12", "成果数": "6", "H指数": "2", "G指数": "3", "研究领域": "计算机图形学/科学计算/人体解剖和组织胚胎学"}{"学者姓名": "刘安丰", "被访人数": "1603人看过", "scholarID": "CN-BG74883J", "工作单位": "中南大学信息科学与工程学院", "被引频次": "1734", "成果数": "195", "H指数": "21", "G指数": "33", "研究领域": "算法理论"}{"学者姓名": "刘连浩", "被访人数": "1421人看过", "scholarID": "CN-B974N4HJ", "工作单位": "中南大学信息科学与工程学院", "被引频次": "579", "成果数": "62", "H指数": "13", "G指数": "20", "研究领域": "信息安全"}{"学者姓名": "刘伟荣", "被访人数": "343人看过", "scholarID": "CN-BL74RMVJ", "工作单位": "中南大学信息科学与工程学院", "被引频次": "324", "成果数": "113", "H指数": "8", "G指数": "16", "研究领域": "分布式与并行计算"}{"学者姓名": "龙军", "被访人数": "1256人看过", "scholarID": "CN-BB7482MJ", "工作单位": "中南大学信息科学与工程学院", "被引频次": "1034", "成果数": "200", "H指数": "14", "G指数": "25", "研究领域": "算法理论"}{"学者姓名": "盛津芳", "被访人数": "283人看过", "scholarID": "CN-BC74YRZJ", "工作单位": "中南大学信息科学与工程学院", "被引频次": "173", "成果数": "57", "H指数": "7", "G指数": "9", "研究领域": "分布式与并行计算"}{"学者姓名": "盛羽", "被访人数": "325人看过", "scholarID": "CN-BR74SK8J", "工作单位": "中南大学信息科学与工程学院", "被引频次": "237", "成果数": "43", "H指数": "9", "G指数": "13", "研究领域": "自然语言处理"}{"学者姓名": "汪洁", "被访人数": "149人看过", "scholarID": "CN-B67332GJ", "工作单位": "中南大学信息科学与工程学院", "被引频次": "144", "成果数": "28", "H指数": "7", "G指数": "11", "研究领域": "计算机网络/信息安全/科学计算"}{"学者姓名": "王斌", "被访人数": "63人看过", "scholarID": "CN-BO74NBSJ", "工作单位": "中南大学信息科学与工程学院", "被引频次": "424", "成果数": "59", "H指数": "13", "G指数": "18", "研究领域": "分布式与并行计算/软件工程"}{"学者姓名": "王国军", "被访人数": "3923人看过", "scholarID": "CN-BK74H3AJ", "工作单位": "中南大学信息科学与工程学院", "被引频次": "5458", "成果数": "540", "H指数": "36", "G指数": "58", "研究领域": "通信与信息系统"}{"学者姓名": "王加阳", "被访人数": "1881人看过", "scholarID": "CN-BB75J89J", "工作单位": "中南大学信息科学与工程学院", "被引频次": "875", "成果数": "148", "H指数": "16", "G指数": "21", "研究领域": "科学计算"}{"学者姓名": "王建新", "被访人数": "10149人看过", "scholarID": "CN-B0747V9J", "工作单位": "中南大学信息科学与工程学院", "被引频次": "8436", "成果数": "1130", "H指数": "38", "G指数": "51", "研究领域": "通信与信息系统"}{"学者姓名": "夏佳志", "被访人数": "503人看过", "scholarID": "CN-BD738FKJ", "工作单位": "浙江大学CADCG国家重点实验室", "被引频次": "297", "成果数": "29", "H指数": "10", "G指数": "16", "研究领域": "算法理论/计算机视觉"}{"学者姓名": "徐德智", "被访人数": "2430人看过", "scholarID": "CN-BK734GUJ", "工作单位": "中南大学信息科学与工程学院", "被引频次": "1266", "成果数": "151", "H指数": "16", "G指数": "30", "研究领域": "科学计算"}{"学者姓名": "余腊生", "被访人数": "785人看过", "scholarID": "CN-BJ75R30J", "工作单位": "中南大学信息科学与工程学院", "被引频次": "417", "成果数": "55", "H指数": "10", "G指数": "18", "研究领域": "软件工程"}{"学者姓名": "张士庚", "被访人数": "1226人看过", "scholarID": "CN-B2742ZCJ", "工作单位": "中南大学信息科学与工程学院", "被引频次": "781", "成果数": "77", "H指数": "14", "G指数": "26", "研究领域": "通信与信息系统"}{"学者姓名": "张修如", "被访人数": "569人看过", "scholarID": "CN-B875OP4J", "工作单位": "中南大学信息科学与工程学院", "被引频次": "249", "成果数": "38", "H指数": "9", "G指数": "15", "研究领域": "算法理论"}{"学者姓名": "张祖平", "被访人数": "880人看过", "scholarID": "CN-B375HKVJ", "工作单位": "中南大学信息科学与工程学院", "被引频次": "474", "成果数": "107", "H指数": "12", "G指数": "16", "研究领域": "数据库"}{"学者姓名": "赵欢喜", "被访人数": "198人看过", "scholarID": "CN-BA745RBJ", "工作单位": "中南大学信息科学与工程学院", "被引频次": "110", "成果数": "31", "H指数": "7", "G指数": "9", "研究领域": "偏微分方程"}{"学者姓名": "赵于前", "被访人数": "1304人看过", "scholarID": "CN-B075ASFJ", "工作单位": "中南大学信息物理工程学院", "被引频次": "926", "成果数": "91", "H指数": "13", "G指数": "27", "研究领域": "生物科学与工程"}{"学者姓名": "郑瑾", "被访人数": "272人看过", "scholarID": "CN-BO74QFPJ", "工作单位": "中南大学信息科学与工程学院", "被引频次": "133", "成果数": "38", "H指数": "7", "G指数": "9", "研究领域": "计算机网络"}{"学者姓名": "周芳芳", "被访人数": "557人看过", "scholarID": "CN-BX75QVPJ", "工作单位": "中南大学信息科学与工程学院", "被引频次": "442", "成果数": "63", "H指数": "11", "G指数": "20", "研究领域": "信息可视化"}{"学者姓名": "邹北骥", "被访人数": "3303人看过", "scholarID": "CN-BO73RN5J", "工作单位": "中南大学信息科学与工程学院", "被引频次": "1962", "成果数": "286", "H指数": "23", "G指数": "32", "研究领域": "算法理论"}

**Comment by konklone** [comment]
This isn't valid JSON - this is multiple JSON objects but with no comma delimiter and no array syntax.
