### ISSUE TITLE
Result set is not auto cleared when input values are made null

### ISSUE THREAD

**Issue by PraveenKuchibhotla** [konklone/json#227]
Result set is not auto cleared when input values are made null

Steps:
1. Provide json data in input text area
2. Data is converted to CSV
3. Clear data from input text area
Defect: result set needs to be reset to blank

**Comment by konklone** [comment]
Why is this important?

**Comment by PraveenKuchibhotla** [comment]
This is a bug hence needs to be fixed. Its upto you when you want to fix it.

Impact: image i am working on fixing a data issue. I execute get API and
fetch the result set. initially i will get 100 records. After some time i
fix some customers and new set will be 90.

When i copy paste a json response to convert it to CSV, initailly i have
100 results. Now i copy result set of 90 to JSON input- how will i know if
result csv have 100 or refreshed to 90.

so before copying the 90 records Json if i wipeout previous json request
then response also should be wiped.

Regards,
Praveen

**Comment by konklone** [comment]
> This is a bug hence needs to be fixed. Its upto you when you want to fix it.

If it's not an important bug and doesn't cause major inconvenience, it doesn't need to be fixed. This is a free service I maintain in my spare time. :) If you'd like to submit a pull request that fixes it, I'll consider it.

> When i copy paste a json response to convert it to CSV, initailly i have 100 results. Now i copy result set of 90 to JSON input- how will i know if result csv have 100 or refreshed to 90.

It shows you the number of total rows in the preview area below, which would indicate that the amount changed.

And even if it were a different dataset with the same number of rows, the app will work properly. When you paste in new data, the CSV output will change. The fact that it doesn't clear out when you clear the data won't affect your actual use of the app.

I'm going to close this, but if you can identify a more serious impact, please feel free to re-open.

**Comment by PraveenKuchibhotla** [comment]
Sounds good. Please close this.
