### ISSUE TITLE
Character Encoding Issue 

### ISSUE THREAD

**Issue by danleecreates** [konklone/json#228]
I have been working with a lot of European names which means there are Spanish, German and French special characters. For example umlaut characters like ö, tiled characters like ñ, acute characters like é and grave characters like à. I noticed these do not get converted properly so for example:

- Wirtschaftsföderung gets changed to Wirtschaftsf√∂derung
- à gets changed to √†

This might be an encoding issue?

**Comment by konklone** [comment]
Hmm - @nearkingdom I can only reproduce this in some CSV applications. 

* Opening the `result.csv` file in `nano` or TextEdit on OS X shows `Wirtschaftsföderung`. 
* Opening it in MS Excel on OS X shows `WirtschaftsfÃ¶derung`.
* You report seeing it as `Wirtschaftsf√∂derung`.

Using it as a key or value renders it properly in the web app:

<img width="596" alt="screen shot 2018-10-30 at 9 12 29 am" src="https://user-images.githubusercontent.com/4592/47720310-f5c38e00-dc23-11e8-9341-bb125ff3dd7d.png">

Are you sure this might not be specific to the client you're using? Or specific to the browser you're using? I'm using Chrome to do the conversion in all of the above cases.

**Comment by konklone** [comment]
Re-open if you have more information.
