### ISSUE TITLE
can you make it more json instagram friendly ?! 

### ISSUE THREAD

**Issue by minanagehsalalma** [konklone/json#232]
https://superuser.com/questions/1412477/how-can-i-view-my-instagram-backup-data-in-a-friendly-way

**Comment by konklone** [comment]
Is there something about it that could be friendlier?

**Comment by minanagehsalalma** [comment]
the instagram  backup ? yes if it's easier to read

**Comment by minanagehsalalma** [comment]
@konklone

**Comment by konklone** [comment]
Sorry, you're going to need to be more specific. Does the JSON from an Instagram export not parse correctly? If it does parse correctly, can you describe what would make it easier to read?

**Comment by minanagehsalalma** [comment]
What would make it easier to read is to make it view the messages/dms just
like what the Instagram do...
You can download your Instagram backup and test yourself   and you will
understand what I mean ;)

**Comment by konklone** [comment]
Got it - well, that would definitely be helpful for Instagram users, but is out of scope for this system. I can't afford to optimize the display of the site for individual services, even if they are fairly popular. The display is really just there as a preview to make sure the CSV was parsed correctly before downloading, not as a real viewer. If there are parsing issues though, please do let me know.
