### ISSUE TITLE
Website is Unable to parse JSON data into CSV

### ISSUE THREAD

**Issue by anand-arch** [konklone/json#239]
This Website is Unable to parse JSON data into CSV, as earlier on March 30, 2019 I can able to convert the JSON data into CSV data. Please find a solution.

![json1](https://user-images.githubusercontent.com/54361412/63688937-4bf26500-c826-11e9-9a59-ceed3857f9ca.png)

**Comment by konklone** [comment]
That's not JSON. If it worked before, then the source you're copy/pasting from changed their format in some way.
