### ISSUE TITLE
JSON to CSV Privacy

### ISSUE THREAD

**Issue by jmf99** [konklone/json#242]
Is data in a JSON file protected from data privacy breaches while uploading and being converted, and is it completely deleted after conversion to CSV or stored somewhere a third party or even GitHub could access it?

**Comment by konklone** [comment]
Hi @jmf99 - reasonable question, and the answer is simple - it's never uploaded at all. The JSON->CSV conversion is done entirely client-side, inside the user's browser. This is what `Your data is never sent to our servers.` means on the top of the page.

This does mean that the app is limited by the user's local memory/CPU on how much JSON data the user can reasonably convert, but it's a very simple solution and I prefer these trade-offs.

An earlier version of the web app had an opt-in "permalink" feature, where the user could generate a permalink to their uploaded data, which would upload the JSON to an anonymous Gist. GitHub stopped supporting that use case, and I removed it from the site.

Let me know if you have any more questions.
