### ISSUE TITLE
Error converting charset ISO 8859-1 

### ISSUE THREAD

**Issue by joaocarlos-pitang** [konklone/json#250]
First of all, congratulations for "JSON to CSV Converter".

When trying to convert a json file with ISO 8859-1 characters, "é" for example, the result comes with a conversion error, in the example, it comes ''Ã©". Is this a error or a local config to ajust?

Sincerely, Joao

**Comment by konklone** [comment]
Are you seeing the `'Ã©` on preview, or also when you open the downloaded CSV? If you specify in your CSV reader that the encoding is ISO 8859-1, does that resolve it?

**Comment by joaocarlos-pitang** [comment]
> Are you seeing the `'Ã©` on preview, or also when you open the downloaded CSV? If you specify in your CSV reader that the encoding is ISO 8859-1, does that resolve it?


it was in preview, but his idea made me think that the problem was before, in the json generation. That's what I did, I generated the json again from another app that did the correct orginal conversion, and then, for cvs using the "JSON to CSV Converter" everything was fine.
Thankful!
