### ISSUE TITLE
My Json  is not converted to csv, what may be the reason?

### ISSUE THREAD

**Issue by katerynasushkova** [konklone/json#252]
I exported trello board to json and wanted to convert to  CSV as suggested [here](https://help.trello.com/article/828-getting-custom-data-from-trello-into-a-spreadsheet) but it didn't work, showing the error: **There was an error parsing this JSON. If you're sure this JSON is valid, please file an issue.**

What could be a problem and how can it be fixed?

**Comment by konklone** [comment]
It's unfortunately impossible to diagnose without an example. Could you share the data you were converting? If you're not comfortable posting it here, you could also email it to me. Or if you're not comfortable doing that, could you sanitize it to share a sample?
