### ISSUE TITLE
Converting JSON to CSV error

### ISSUE THREAD

**Issue by MaiconBruce** [konklone/json#256]
Hello, guys!

Please, I need a help: I would like to migrate a Trello table to Microsoft Planner, so, I tried to export the  table in a JSON format and paste the data in the konklone converter.
However, an error message appeared: "There was an error parsing this JSON" and the JSON did not appear as a table.

Please, could you guys check this out?

Thanks,
Maicon

**Comment by konklone** [comment]
Could you share the JSON you're trying to convert?

-- Eric

**Comment by MaiconBruce** [comment]
[JSON.txt](https://github.com/konklone/json/files/6823107/JSON.txt)

**Comment by konklone** [comment]
Yeah, this JSON looks really broken - many of its lines are clearly truncated and missing data. It's not recoverable and this tool can't possibly turn it into a CSV. There's almost certainly some kind of problem in what you exported, or in any copy/pasting or other transformation you did on the way to creating this data. So unfortunately I think you will need to investigate the export process on your end.

**Comment by MaiconBruce** [comment]
Ok! Thanks
