### ISSUE TITLE
Command line version via npm

### ISSUE THREAD

**Issue by konklone** [konklone/json#30]
Not to compete with `csvkit` exactly, but it might be useful to take the existing JS and wrap it up in an npm module. If it's structured right, then any improvements to the browser version should improve the npm version without any extra work (beyond an `npm publish` command).

Low priority. But if the JSON is too big and we warn the user (#29) then maybe we can point them to this. It's nice to have an alternative if people want to process [hub.healthdata.gov/data.json](http://hub.healthdata.gov/data.json).

**Comment by stevemao** [comment]
Yeah it's also easier for browserify and webpack users if this is published to npm.
