### ISSUE TITLE
Advanced override using JavaScript

### ISSUE THREAD

**Issue by jonrobinson2** [konklone/json#31]
Allow advanced users to provide a snippet of JavaScript that does custom mapping of "rows". Necessary to handle cases like the one described below (and others that have been reported).

---

Original ticket:

https://raw.github.com/csaid/economist_poll/master/survey_results.json

This is the file I'd like to play with. I paste it into the browser and just get a csv that is one row by 4,000. This isn't my JSON, but am curious if it's the person who compiled  it's fault or some kind of quirk of the parser.

Thanks!

**Comment by konklone** [comment]
This is exactly the sort of JSON the parser can't handle right now, where there are no arrays involved, and keys/values are used to define unordered sets. I'd love to make this possible for the parser, whether it involves advanced user customization or not. 

What do you think the resulting CSV **should** look like? Can you mock up an excerpt in text, here in the thread?

**Comment by jonrobinson2** [comment]
This is a bit of a complex data file. I agree it should involve some user customization..

| column | q_url_suffix | economist | response |
| --- | --- | --- | --- |
| "(001) All else equal, the Fed's new plan to increase the maturity of its Treasury holdings will boost expected real GDP growth for calendar year 2012 by at least one percentage point." | SV_9yFWHquReQZjC6w | Daron Acemoglu | Disagree |

**Comment by jonrobinson2** [comment]
This is basically making the data very long so it can then be reshaped, etc in whatever programming language is necessary.

**Comment by konklone** [comment]
Maybe I could let advanced users put in a little JavaScript snippet to do some mapping, that'd be real interesting. Like, write the innards of a function that gets a "row", and is allowed to reorganize it before passing it on (this would be necessary to define field names that don't appear in the source, like `economist` and `response`).

**Comment by jonrobinson2** [comment]
Would be cool. I'm not a JavaScript person, but if you provided a little example I'm sure I could figure it out.

**Comment by konklone** [comment]
OK, well I don't know if I'm going to get to it immediately, but I just updated the ticket title and description to reflect the desired fix.

**Comment by jonrobinson2** [comment]
Cool stuff. Thanks!
