### ISSUE TITLE
Command Line Interface

### ISSUE THREAD

**Issue by jeffmarcilliat** [konklone/json#38]
Any thoughts about enabling this in the command line?

**Comment by konklone** [comment]
That's covered in #30, so I'm going to close as a duplicate.

But right now, I think [csvkit](http://csvkit.readthedocs.org/en/latest/scripts/in2csv.html) covers the command line interface pretty well, so I don't feel like there's a lot of value there. Still, if someone went to the trouble to package this up into an `npm` module with a CLI interface, I'd help publish it. But it'd take some refactoring, too -- and the dependency on jquery and jquery-csv is big and unnecessary.
