### ISSUE TITLE
nothing happens when I pasted json in the top box

### ISSUE THREAD

**Issue by bdegraf** [konklone/json#39]
There doesn't seem to be any submit event.

**Comment by konklone** [comment]
It should try to auto-transform the content when you paste in content, or at worst case if you unfocus the text box. (It tries to catch the `onpaste` event, and then also catches the `onblur` event.)

Can you create a permalink to your content using the link at the top (it'll save your content even if it didn't get transformed), and post it here?

**Comment by bdegraf** [comment]
thanks, I made one at http://konklone.io/json/?id=97633f7946f33f88f983
The auto-transform would be nice, but I just don't see how to submit it by hand. There's no 'submit' button anywhere that I can see.

**Comment by konklone** [comment]
So it looks like it's because the JSON uses single quotes and not double quotes, which isn't technically valid. However, obviously, it should tell you what the error is. I'm going to close this in favor of #7, which is about setting up a graceful error process. Thanks for reporting this!
