### ISSUE TITLE
allow key override

### ISSUE THREAD

**Issue by konklone** [konklone/json#4]
Right now it just finds the first array field at the top level and uses that as the "record". But for something like

> http://project-open-data.github.io/schema/1_0_final/single_entry.json

That doesn't work. Allowing an override of which key to use as the top (which [in2csv](http://csvkit.readthedocs.org/en/latest/scripts/in2csv.html), this project's inspiration, does) would solve this.

**Comment by konklone** [comment]
And @vzvenyach provides http://dccode.org/browser/sections/1-206.02.json in #9 as a perfect example of why specifying what field should be the "record" is needed.

**Comment by Klortho** [comment]
+1.  [Another example](http://konklone.io/json/?id=9457288)
