### ISSUE TITLE
jquery.min.map path not found

### ISSUE THREAD

**Issue by rootedsoftware** [konklone/json#43]
Please check the resource paths on your server, my browsers couldn't seem to find jquery-1.10.2.min.map.

GET http://konklone.io/json/assets/jquery-1.10.2.min.map 404 (Not Found)

**Comment by rootedsoftware** [comment]
I found this, it should help. http://stackoverflow.com/questions/18365315/jquerys-jquery-1-10-2-min-map-is-triggering-a-404-not-found

**Comment by konklone** [comment]
Will do. For reference, this _only_ affects developer console users. The request to fetch the map is triggered **by** the developer console.

**Comment by konklone** [comment]
I updated to jQuery 2.1.1, and added the map file, in https://github.com/konklone/json/commit/ed82c1232cc3d467fb18b900ad9c658bd639e53d. Thanks for flagging this!
