### ISSUE TITLE
 Converting error

### ISSUE THREAD

**Issue by zhrivodkin** [konklone/json#45]
Hi! Im trying to convert example from wikipedia:

```
{
   "firstName": "Иван",
   "lastName": "Иванов",
   "address": {
       "streetAddress": "Московское ш., 101, кв.101",
       "city": "Ленинград",
       "postalCode": 101101
   },
   "phoneNumbers": [
       "812 123-1234",
       "916 123-4567"
   ]
}
```

and get only phoneNumbers: http://take.ms/rC6vm

**Comment by konklone** [comment]
Yeah, the converter needs to operate on an array, for right now. It looks for the first array it finds in the dataset. I'm not sure what the best algorithm for this is -- I have one approach in #31 to deal with it. 

What output were you hoping to see?

**Comment by zhrivodkin** [comment]
I think It would be logical to get an array as a sequence of its elements separated by commas.
