### ISSUE TITLE
allow pasting of URL instead of JSON body

### ISSUE THREAD

**Issue by konklone** [konklone/json#5]
fetched with CORS, error out if it doesn't work.

specifically, don't try JSONP

**Comment by konklone** [comment]
for advanced mode only

**Comment by danmunz** [comment]
Now that I read it, I suppose this could take the place of #24.

**Comment by konklone** [comment]
Well, there's so much out there that doesn't support CORS (or JSONP), I don't know how reliable this approach would be. I'd like to introduce this into the UX for advanced users who won't get scared by the use of the term "CORS". I don't know if it'd replace #24 either way.
