### ISSUE TITLE
Converting json to csv files  for very larg files 

### ISSUE THREAD

**Issue by vthummadi** [konklone/json#50]
I can convert the json to csv in the web browser but i have a very large files and i tried using | in2csv -f json  -v > data.csv and i donot  get all the columns which i get through the browser. How should i specify the code if am using a curl command? I checked the documentation but there is not enough explanation on converting the json to csv.

**Comment by konklone** [comment]
You can't use a curl command with this site - it doesn't offer an API.

I don't know why you wouldn't get the same columns using `in2csv`. Could you post an example of a sample of your input JSON, and example output with both this tool and with `in2csv`?

**Comment by vthummadi** [comment]
I am attaching the json files(commits), csvfile generated using in2csv
command(issues.csv) and using json to csv using the web
version(results.csv).  I have used the command as per Github site (in2csv
-f json > issues.csv) along with curl.

**Comment by konklone** [comment]
@vthummadi You can't attach them via email. You need to visit the web interface for this ticket (https://github.com/konklone/json/issues/50) and paste the contents in.

**Comment by vthummadi** [comment]
These are web results with json file in it(web version).
http://konklone.io/json/?id=2da18c662285a0e6be0f.
But when i use in2csv -f json > issue.csv i get only few columns and i don't get values for author this way.
--sha commit url html_url comments_url author committer parents

**Comment by konklone** [comment]
:( I'm sorry, I just did some research and I don't know. But this looks like a bug with `in2csv`. You should raise an issue over there, and reference this one:

https://github.com/onyxfish/csvkit/issues
