### ISSUE TITLE
Nested objects make Firefox hang on line 49

### ISSUE THREAD

**Issue by CoDEmanX** [konklone/json#51]
Enter the following JSON:

```
{"foo": "bar", "sub": {}}
```

It will make Firefox hang at

```
        for (var key in next)
```

**Comment by konklone** [comment]
Wow! It crashes Chrome too. That's gnarly. Got a suggested replacement? Otherwise, I'll dive in when I have a bit of downtime.

**Comment by CoDEmanX** [comment]
It seems to loop over the object until it finds an array. If there's at least one, it stops to hang/crash and will simply ignore nested objects.

I didn't check the entire code, so not sure how to fix it best. Shouldn't be more than a simple condition to stop looking for arrays if there are none. Maybe test for type in that for loop to ignore objects? `ob.constructor === Array`

**Comment by konklone** [comment]
This works now.
