### ISSUE TITLE
Recent change to CSV format?

### ISSUE THREAD

**Issue by Tom11111** [konklone/json#55]
Hi. We have been transforming JSON files to CSV at your site (thanks!). It placed the variable labels and then the values in two two nice rows…but today it is just returning a single word from the file - exactly the same files that last week it converted as described. Has there been a recent change? Thanks very much. Tom11111

**Comment by konklone** [comment]
@Tom11111 I did make a recent change, last night to fix a bug with detecting which elements should be "rows":

https://github.com/konklone/json/issues/54

Sounds like I may have caused a regression. Can you show me an example of the data, so I can test against it?

This is a good reminder to make a command-line (Node) wrapper around the core library, and to make a tiny test suite to prevent possible regressions.

cc @vzvenyach

**Comment by evanplaice** [comment]
FYI, this is repo is using an outdated version of jquery-csv. The you might try the latest from http://github.com/evanplaice/jquery-csv.
