### ISSUE TITLE
Permalinks should detect truncated gist content and fetch full raw content

### ISSUE THREAD

**Issue by swanson** [konklone/json#62]
Visit this page: https://sports.yahoo.com/dailyfantasy/api/resource/dailyfantasy.players;contestId=22306

Paste that content into the site and it works great. But when I try to create a permalink and reload the page, not all of the content is copied over so the CSV conversion does not work.

Directly pasting in:

![image](https://cloud.githubusercontent.com/assets/56947/8809669/24d03138-2fb8-11e5-96c1-adedf945f38f.png)

Using permalink: http://konklone.io/json/?id=8ed32e80cd9408d29987

![image](https://cloud.githubusercontent.com/assets/56947/8809815/ea45052e-2fb8-11e5-9d8b-4db1fd31fb52.png)

Any ideas what might be happening?

Windows 8.1
Chrome 43

**Comment by konklone** [comment]
It looks to me like this is a Gist limitation. If you visit your permalink in the converter, you can see that the input is truncated from what you saved. If you visit the Gist that backs your permalink, you can see that GitHub truncates it in the display to the exact same character as it's truncated in the converter (which gets its content from the Gist API).

https://gist.github.com/anonymous/8ed32e80cd9408d29987

And if you look in the Gist API, the API does indeed truncate it to the same place:

https://api.github.com/gists/8ed32e80cd9408d29987

Gist does provide the full content of what you saved, if you [click through](https://gist.githubusercontent.com/anonymous/8ed32e80cd9408d29987/raw/b9259234a86b0a5a3488f8bb865a40026ba38fea/source.json) to the full raw data.

I can also see that the [Gist API](https://api.github.com/gists/8ed32e80cd9408d29987) provides a `truncated` field, marked `true` in the response above. So, the converter could look for that field and then make a second request to fetch the full data from a Gist. I've confirmed that `gist.githubusercontent.com` has CORS headers set, and we should be okay to do that with our static page.

I'm renaming the issue to make it reflect what it would take to fix this. Up for submitting a PR for it? I can also do this, but it'll probably need to wait until the weekend.
