### ISSUE TITLE
allow multiple roots

### ISSUE THREAD

**Issue by udii** [konklone/json#64]
parse multiple json objects in one file, which is quite common in real life, e.g.
{age: 12, height: 140}
{age: 14, height: 155}
{age: 13, height: 150}

(I know this is not a valid json, and that should have been an array using [] notion, still in many cases users have a stream of json objects)

Thanks for a very useful tool, btw

**Comment by konklone** [comment]
There, I think you're asking for the parser to detect "json lines" and sort
of add a virtual root above them, right?

**Comment by udii** [comment]
Basically yes, I am suggesting that in case there are multiple json roots, instead of failing we will parse them as if they were a json array, or as you suggested a json object with an array.

Here are a few examples:

Example of multiple json roots, currently those failed to be parsed in your tool:
{"age": 12, "height": 140}
{"age": 14, "height": 155}
{"age": 13, "height": 150}

Example of the same data as a json array, currently this would parse successfully:
[{"age": 12, "height": 140},
{"age": 14, "height": 155},
{"age": 13, "height": 150}]

Example of the same data as a json object with an array, currently this would also be parse successfully:
{ "data":[
  {"age": 12, "height": 140},
  {"age": 14, "height": 155},
  {"age": 13, "height": 150}
  ]
}

**Comment by konklone** [comment]
@udii This is resolved in #67. Give it a shot?

This permalink has a (modified) version of the JSON Lines you provided:
http://konklone.io/json/?id=0700c7c0d159a5da81e0
