### ISSUE TITLE
It's broken.

### ISSUE THREAD

**Issue by scottmunro** [konklone/json#65]
JSON to CSV conversion not working at all. JSON is pasted in, but no output returned. 

Same JSON blob is converting properly to CSV here: https://json-csv.com/ (You have a better UX though, so would rather use your site)

Windows Chrome Version 48.0.2564.109 m
Last tried about 2016-02-19 16:20 PST

**Comment by konklone** [comment]
@scottmunro Can you provide the JSON you're pasting in? 

Some trivial JSON does work:
http://konklone.io/json/?id=76d9931ab062247ce5bf

**Comment by scottmunro** [comment]
This is representative of the whole JSON, which is probably a bit too work-specific to include in full.

Regardless, this snippet behaves the same way. Doesn't work with your tool, works at the other one:

{
uuid: "ABC123",
name_space: "namespace",
title: "Example",
description: "Global rate of Examples",
formula: "Example / Foo",
aggregation: "RATIO",
tags: [
"MARKETPLACE"
],
unit: "%",
meta: { }
},

**Comment by konklone** [comment]
@scottmunro After I merged #66, your example works now:

http://konklone.io/json/?id=41148dc8ca9f6771d4e2

Thank you so much for filing this issue -- it motivated me to make the site much better and more flexible!

**Comment by scottmunro** [comment]
Thanks for tackling it so quickly! This is a great tool - it saves a huge amount of time for those of us who work with JSON frequently but specialize in visual data organization (eg Excel) and want to scrape / organize the data quickly.

Interesting to know that I wasn't working with pure JSON either. This is how Chrome interpreted the JSON file when I opened it in-browser. In the future I'll open with a text-editor instead before copy/pasting into your tool. Doing that works perfectly now.

Thanks again!

**Comment by konklone** [comment]
It may be that you have the JSON View Chrome extension installed?

If so, you may wish to use the [JSON Formatter Chrome extension](https://chrome.google.com/webstore/detail/json-formatter/bcjindcccaagfpapjjmafapmmgkkhgoa?hl=en) instead, which I use specifically because it leaves keys properly quoted for copy/paste (while being just as helpful and easy to use).

**Comment by scottmunro** [comment]
Bingo, that extension worked - thanks!
