### ISSUE TITLE
Graceful error

### ISSUE THREAD

**Issue by konklone** [konklone/json#7]
Right now, it just displays nothing. Say something if the conversion fails.

**Comment by dvogel** [comment]
It should always say something when conversion fails but it should say something special for valid JavaScript that is invalid JSON. These are especially common errors. For example `{'k':'v'}` is invalid JSON since double-quotes are required for strings in JSON. You can detect this class of error by checking if `eval()` succeeds. Since the user is supplying the data, `eval()` _should_ be safe.

**Comment by konklone** [comment]
For reference, this thread backs @dvogel up as `eval()` being the only way:

http://stackoverflow.com/questions/9036429/convert-object-string-to-json

**Comment by konklone** [comment]
So I did a first pass of this in https://github.com/konklone/json/commit/db66e5cde36b9cc8c4ad3f0723656c98c300bba2 and it'll probably handle lots of these cases. It handles pasting in from JSONView in most cases, for instance.

But @dvogel, curious about your take on [this bill](http://congress.api.sunlightfoundation.com/bills?apikey=sunlight9&per_page=1&page=5) has a string with a quote inside it. In the raw JSON, it's escaped, but in JSONView, it's displayed directly, so a quick copy/paste breaks even on `eval()`. Any ideas?

**Comment by dvogel** [comment]
That bills looks properly escaped to me. It's valid JSON. It's properly converted for me. Are you sure you didn't copy/paste from the parsed output from JSONView?

**Comment by konklone** [comment]
That was the point, to get something that would accept pastes from JSONView. And at your (offline) suggestion, I'll go with [JSON Formatter](https://chrome.google.com/webstore/detail/json-formatter/bcjindcccaagfpapjjmafapmmgkkhgoa?hl=en) for Chrome. There is no JSON Formatter port for Firefox.

But actually! I just tried JSONView on Firefox, and it behaves perfectly. Leaves escaped quotes, doesn't copy the dashes. So at least for my particular workshop, I'm okay. I'm going to close this, and if someone comes at me with an edge case for JSONView on Chrome, they can open a new issue.

**Comment by konklone** [comment]
Re-opening -- this doesn't address the issue's original concern, which is telling the user about parse errors (including syntax errors from truncated or otherwise invalid JSON).
