### ISSUE TITLE
Parsing a huge JSON string with multiple entries

### ISSUE THREAD

**Issue by kadimulam** [konklone/json#74]
I have s JSON data mentioned below which has a complex structure. In some cases, it might include array of elements, sub elements etc. When i used the online tool (http://konklone.io/json/), it is converting only the Array elements (ie phoneNumber) and excluding the upper portion of the JSON. I need some way of converting this complex JSON to CSV. Could you please let me know if it possible with this API?

{
     "firstName": "John",
     "lastName": "Smith",
     "age": 25,
     "address":
     {
         "streetAddress": "21 2nd Street",
         "city": "New York",
         "state": "NY",
         "postalCode": "10021"
     },
     "phoneNumber":
     [
         {
           "type": "home",
           "number": "212 555-1234"
         },
         {
           "type": "fax",
           "number": "646 555-4567"
         }
     ]
 }

**Comment by konklone** [comment]
The tool tries to "find the array" in any JSON it's given. When you put in that data above, alone, it hops to the first array it sees, which is the phone number info.

If you want this tool to process your JSON, you should give it an array where each object in it is the item above. This means the JSON you paste in should begin with a `[` and end with a `]`. If you were to add a `[` and `]` around your JSON above, you would get a one-row CSV with all the information in the JSON object.

**Comment by kadimulam** [comment]
Yes Konklone, when i begin with a [ and end with a ], i am able to convert to CSV. Could you please let me know if you have a tool to process the reverse also? I mean converting from CSV to JSON. Or just point me any Github project online.

**Comment by konklone** [comment]
The best thing I can think of is Mr. Data Converter: https://shancarter.github.io/mr-data-converter/

**Comment by konklone** [comment]
http://www.csvjson.com/csv2json may also work for your needs.

**Comment by kadimulam** [comment]
I tried both the tools yesterday and now also. The issue with these tools is they are taking the header name AS-IS and constructing the JSON element. For instance, when i convert the above JSON to spreadsheet with your tool, it provides four columns phoneNumber/0/type,phoneNumber/0/number,phoneNumber/1/type,phoneNumber/1/number for Phone Number Array. This is correct, however when i try to convert these four columns to JSON back with any of the above two tools, it creates a JSON like below which is incorrect. It needs to create one phoneNumber Array, but it is creating two different elements.If you see "address" element, it is also incorrect based on the original JSON.

[{"firstName":"John","lastName":"Smith","age":25,"address/streetAddress":"25 2nd Street","address/city":"New York","address/state":"NY","address/postalCode":10021,"phoneNumber/0/type":"home",**"phoneNumber/0/number":"212 555-1234","phoneNumber/1/type":"fax","phoneNumber/1/number":"646 555-4567"**}]

**Comment by konklone** [comment]
Unfortunately, there's nothing this project can do about that -- we're just focused on JSON -> CSV.
