### ISSUE TITLE
Error parsing some specific JSON

### ISSUE THREAD

**Issue by VivaBem** [konklone/json#75]
I'm having an issue converting this JSON. The problem is caused by the ":":

``` json
{
date:"19/09/2012 12:34:56"
}
```

**Comment by konklone** [comment]
Yeah, you will need to quote the `date` field:

``` json
{
"date": "19/09/2012 12:34:56"
}
```

I do have some code that tries to auto-fix missing quotes, but in this case it won't work with JSON that also uses colons in the middle of the string like that. There's only so much I can do to fix invalid JSON that way.
