### ISSUE TITLE
Error parsing some specific JSON

### ISSUE THREAD

**Issue by Hodanr** [konklone/json#77]
I'm having an issue converting this JSON:

http://konklone.io/json/?id=843dd2742a815b0d2dadadf96718b55a

**Comment by konklone** [comment]
Your keys are quoted using single quotes instead of double quotes, which isn't valid JSON. Is it easy for you to fix this?

**Comment by Hodanr** [comment]
yes, yes sure.
Thank you :)

**Comment by konklone** [comment]
:+1: :)
