### ISSUE TITLE
Error parsing some specific JSON

### ISSUE THREAD

**Issue by anandshah123** [konklone/json#80]
I'm having an issue converting this JSON:

http://konklone.io/json/?id=24dbef6b73c46cf233f65738963945f3

**Comment by konklone** [comment]
Interestingly, it looks to be something weird about your whitespace.

This JSON works fine: http://konklone.io/json/?id=b3c6403042aa649ec1648f85d15b7019

But this JSON, the same data and formatting, but with whitespace I copy and pasted from your JSON, does not: http://konklone.io/json/?id=2b641dab78003bd75af488359751a672

I will look into why this is and try to address it, but you may want to consider fixing whatever's causing your whitespace issues in the meantime.

**Comment by anandshah123** [comment]
Worked for me after removing spaces. I think it's just whitespace issue.
