### ISSUE TITLE
Error Downloading File

### ISSUE THREAD

**Issue by fawadakhtar** [konklone/json#83]
When the data Json data exceeds 2 mb I am unable to download the file. I get the error Failed- Network error in chrome. However works fine when data is less than 1 mb.

**Comment by demiangreen** [comment]
Me to! Please fix (((

**Comment by fawadakhtar** [comment]
Instead of waiting for someone to fix the konklone, what is did was to download openrefine and convert my json file to csv through it. It's a great tool for data cleaning.

**Comment by konklone** [comment]
There's no 2mb limit. You'll need to be more specific for me to have something to fix.
