### ISSUE TITLE
What options are you using for in2csv

### ISSUE THREAD

**Issue by RickCogley** [konklone/json#90]
Hello - I tried using your tool, but the size of data I have crashes my browser. 

I'm wondering, could you kindly tell me what arguments you're using on in2csv, to generate the csv on the page? 

I ask because, the standard in2csv in a Terminal gives fewer fields, as though there is a "depth" argument specified on your site, to return various deeper fields in the json. 

Sincerely,
Rick

**Comment by konklone** [comment]
I'm not using in2csv (though I give it credit for inspiration), and as of right now, in2csv doesn't do recursive flattening of JSON objects, so it won't give you the same output.

in2csv _used_ to support recursive flattening in an earlier version, and I don't know why they dropped it. The maintainer didn't know either when I asked him!

I implemented recursive flattening myself in JavaScript, using in2csv's old Python as a guide, along with array-finding logic:

https://github.com/konklone/json/blob/3733960124768ad27c3bf114c7af03464aded1f5/assets/site.js#L23-L81

You could turn that into a Node tool to do what you want. If you turned it into a module that I could pull back into the website, that'd be awesome from an open source perspective. Others have wanted the same kind of module.

**Comment by RickCogley** [comment]
Hi Eric - thanks for the answer. I need it, but, I'm not sure I know what
to do to make a node module, I'm afraid.
When the project I need this for comes on line, I'll see what I can do at
that time.
Kind regards,
Rick
