### ISSUE TITLE
Error parsing some specific JSON

### ISSUE THREAD

**Issue by ciberbob1987** [konklone/json#91]
I'm having an issue converting this JSON:

http://konklone.io/json/?id=87652024e1a8c0cfefbd59a53cf57033

**Comment by konklone** [comment]
This JSON looks incomplete. It's at least missing some outside brackets `[` and `]`, but it appears to be missing more than that. This JSON is very large, so I would recommend trying to test it with a small subset of the JSON and figuring out what's missing, and then applying the same fix to the larger JSON sample.
