### ISSUE TITLE
Nested JSON format

### ISSUE THREAD

**Issue by subhashisrouth** [konklone/json#92]
Hello sir,
below json can not be formatted,

{  
   "jobTitle":"Android app development",
   "companyName":"ss",
   "jobDescription":"I need an app",
   "salary":0,
   "categoryId":41,
   "serviceProviderDetailsId":12,
   "videoUrl":"http://res.cloudinary.com/ineedayuda/video/upload/v1468845843/nlduu2p8psqtmyvcvqg11.mp4",
   "fileBeans":[  
      {  
         "imageUrl":"http://res.cloudinary.com/ineedayuda/image/upload/v1468845824/moekamatr87ne5ylpfsq1.png"
      },
      {  
         "imageUrl":"http://res.cloudinary.com/ineedayuda/image/upload/v1468845825/dfuflf0ke7rxkphiqco91.jpg"
      },
      {  
         "imageUrl":"http://res.cloudinary.com/ineedayuda/image/upload/v1468845825/e8fnbirtko9kfinuofdp1.jpg"
      },
      {  
         "imageUrl":"http://res.cloudinary.com/ineedayuda/image/upload/v1468845826/za5jqojqv0heebkinaa71.jpg"
      },
      {  
         "imageUrl":"http://res.cloudinary.com/ineedayuda/image/upload/v1468845825/ao2gyrbqpb5uadxjyuue1.jpg"
      }
   ]
}

do I made something wrong with json format

**Comment by konklone** [comment]
It works for me: https://konklone.io/json/?id=92eb174bd59acfe9001e390d51040290
