### ISSUE TITLE
Error parsing some specific JSON

### ISSUE THREAD

**Issue by prashantgavhane** [konklone/json#94]
I'm having an issue converting this JSON:

var tabMappings = {
        1: {
            categoryName: "Home Decor",
            tabName: "Pick a Room",
            tabId: "pickARoom"
        },
        2: {
            categoryName: "Apparel",
            tabName: "Pick a Style",
            tabId: "pickAFabric"
        }
    };
var materials = [
        {
            materialId: 1,
            materialName: "Spandex"
        },
        {
            materialId: 2,
            materialName: "Rayon"
        },
        {
            materialId: 3,
            materialName: "Blended"
        }
    ];
var demoSchema = {
        1: {                            // This category will be loaded if the url is demo/1
            categoryName: "Home Decor",
            subCategories: [
                {
                    id: 1,
                    subCategoryName: "Bedroom",
                    subCategoryItems: [
                        {
                            id: 1,
                            itemName: "Double Bed",
                            mainImageUrl: "assets/processed/Bedroom/Main_Image/BR_DB_1.jpg",
                            mainImageTh: "assets/processed/Bedroom/Main_Image/BR_DB_1_T.jpg",
                            positions: [
                                {
                                    posId: "BL",    // BL stands for blanket
                                    coordX1: "10",  // in percent
                                    coordY1: "50",  // in percent
                                    coordX2: "80",  // in percent
                                    coordY2: "90"  // in percent
                                },
                                {
                                    posId: "PC",    // PC stands for pillow covers
                                    coordX1: "40",  // in percent
                                    coordY1: "30",  // in percent
                                    coordX2: "80",  // in percent
                                    coordY2: "50"   // in percent
                                }
                            ],
                            patterns: [
                                {
                                    materialId: 1,    // this should be one of the ids from the above materials block
                                    url: "assets/processed/Bedroom/BR_DB_REG_1_001T.jpg",
                                    BL: "assets/processed/Bedroom/Overlay_images/BR_DB_BL_REG_1_001.png",
                                    PC: "assets/processed/Bedroom/Overlay_images/BR_DB_PC_REG_1_001.png"
                                },
                                {
                                    materialId: 1,
                                    url: "assets/processed/Bedroom/BR_DB_REG_1_002T.jpg",
                                    BL: "assets/processed/Bedroom/Overlay_images/BR_DB_BL_REG_1_002.png",
                                    PC: "assets/processed/Bedroom/Overlay_images/BR_DB_PC_REG_1_002.png"
                                },
                                {
                                    materialId: 1,
                                    url: "assets/processed/Bedroom/BR_DB_REG_1_003T.jpg",
                                    BL: "assets/processed/Bedroom/Overlay_images/BR_DB_BL_REG_1_003.png",
                                    PC: "assets/processed/Bedroom/Overlay_images/BR_DB_PC_REG_1_003.png"
                                }
                            ]
                        }
                    ]
                },
                {
                    id: 2,
                    subCategoryName: "Kids room",
                    subCategoryItems: [
                        {
                            id: 2,
                            itemName: "Single Bed",
                            mainImageUrl: "assets/processed/Kids_room/Main_Image/KR_SB_1.jpg",
                            mainImageTh: "assets/processed/Kids_room/Main_Image/KR_SB_1_T.jpg",
                            positions: [
                                {
                                    posId: "BL",
                                    coordX1: "0",
                                    coordY1: "72",
                                    coordX2: "45",
                                    coordY2: "100"
                                }, // BL stands for blanket
                                {
                                    posId: "PC",
                                    coordX1: "5",
                                    coordY1: "60",
                                    coordX2: "30",
                                    coordY2: "72"
                                }
                            ],
                            patterns: [
                                {
                                    materialId: 1,
                                    url: "assets/processed/Kids_room/KR_SB_REG_1_001T.jpg",
                                    BL: "assets/processed/Kids_room/Overlay_images/KR_SB_BL_REG_1_001.png",
                                    PC: "assets/processed/Kids_room/Overlay_images/KR_SB_PC_REG_1_001.png"
                                },
                                {
                                    materialId: 1,
                                    url: "assets/processed/Kids_room/KR_SB_REG_1_002T.jpg",
                                    BL: "assets/processed/Kids_room/Overlay_images/KR_SB_BL_REG_1_002.png",
                                    PC: "assets/processed/Kids_room/Overlay_images/KR_SB_PC_REG_1_002.png"
                                },
                                {
                                    materialId: 1,
                                    url: "assets/processed/Kids_room/KR_SB_REG_1_003T.jpg",
                                    BL: "assets/processed/Kids_room/Overlay_images/KR_SB_BL_REG_1_003.png",
                                    PC: "assets/processed/Kids_room/Overlay_images/KR_SB_PC_REG_1_003.png"
                                }
                            ]
                        }
                    ]
                },
                {
                    id: 3,
                    subCategoryName: "Living room",
                    subCategoryItems: [
                        {
                            id: 3,
                            itemName: "Door Curtains & Cushions",
                            mainImageUrl: "assets/processed/Living_room/Main_Image/LR_DC_1.jpg",
                            mainImageTh: "assets/processed/Living_room/Main_Image/LR_DC_1_T.jpg",
                            positions: [
                                {
                                    posId: "DC",
                                    coordX1: "0",
                                    coordY1: "0",
                                    coordX2: "30",
                                    coordY2: "47"
                                }, // BL stands for blanket
                                {
                                    posId: "CC",
                                    coordX1: "8",
                                    coordY1: "49",
                                    coordX2: "37",
                                    coordY2: "65"
                                }
                            ],
                            patterns: [
                                {
                                    materialId: 1,
                                    url: "assets/processed/Living_room/LR_DC_REG_1_001T.jpg",
                                    DC: "assets/processed/Living_room/Overlay_images/LR_DC_REG_1_001.png",
                                    CC: "assets/processed/Living_room/Overlay_images/LR_CC_REG_1_001.png"
                                },
                                {
                                    materialId: 1,
                                    url: "assets/processed/Living_room/LR_DC_REG_1_002T.jpg",
                                    DC: "assets/processed/Living_room/Overlay_images/LR_DC_REG_1_002.png",
                                    CC: "assets/processed/Living_room/Overlay_images/LR_CC_REG_1_002.png"
                                },
                                {
                                    materialId: 1,
                                    url: "assets/processed/Living_room/LR_DC_REG_1_003T.jpg",
                                    DC: "assets/processed/Living_room/Overlay_images/LR_DC_REG_1_003.png",
                                    CC: "assets/processed/Living_room/Overlay_images/LR_CC_REG_1_003.png"
                                }
                            ]
                        },
                        {
                            id: 4,
                            itemName: "Door Curtains & Cushions Two",
                            mainImageUrl: "assets/processed/Living_room/Main_Image/LR_DC_2.jpg",
                            mainImageTh: "assets/processed/Living_room/Main_Image/LR_DC_2_T.jpg",
                            positions: [
                                {
                                    posId: "CC",
                                    coordX1: "10",
                                    coordY1: "44",
                                    coordX2: "48",
                                    coordY2: "60"
                                },
                                {
                                    posId: "DC",
                                    coordX1: "56",
                                    coordY1: "25",
                                    coordX2: "67",
                                    coordY2: "55"
                                }
                            ],
                            patterns: [
                                {
                                    materialId: 1,
                                    url: "assets/processed/Living_room/LR_DC_REG_2_001T.jpg",
                                    DC: "assets/processed/Living_room/Overlay_images/LR_DC_REG_2_001.png",
                                    CC: "assets/processed/Living_room/Overlay_images/LR_CC_REG_2_001.png"
                                },
                                {
                                    materialId: 1,
                                    url: "assets/processed/Living_room/LR_DC_REG_2_002T.jpg",
                                    DC: "assets/processed/Living_room/Overlay_images/LR_DC_REG_2_002.png",
                                    CC: "assets/processed/Living_room/Overlay_images/LR_CC_REG_2_002.png"
                                },
                                {
                                    materialId: 1,
                                    url: "assets/processed/Living_room/LR_DC_REG_2_003T.jpg",
                                    DC: "assets/processed/Living_room/Overlay_images/LR_DC_REG_2_003.png",
                                    CC: "assets/processed/Living_room/Overlay_images/LR_CC_REG_2_003.png"
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        2: {        // This category will be loaded if the url is demo/2
            categoryName: "Apparel",
            subCategories: [
                {
                    id: 1,
                    subCategoryName: "Western Wear",
                    subCategoryItems: [
                        {
                            id: 4,
                            itemName: "Skirts_SK1",
                            mainImageUrl: "assets/processed/SkirtsModified/Main_Image/WW_SK_1.jpg",
                            mainImageTh: "assets/processed/SkirtsModified/Main_Image/WW_SK_1_T.jpg",
                            positions: [
                                {
                                    posId: "SK",
                                    coordX1: "40",
                                    coordY1: "52",
                                    coordX2: "70",
                                    coordY2: "92"
                                }
                            ],
                            patterns: [
                                {
                                    materialId: 1,
                                    url: "assets/processed/SkirtsModified/WW_SK_REG_1_001T.jpg",
                                    SK: "assets/processed/SkirtsModified/Overlay_Images/WW_SK_REG_1_001.png"
                                },
                                {
                                    materialId: 1,
                                    url: "assets/processed/SkirtsModified/WW_SK_REG_1_002T.jpg",
                                    SK: "assets/processed/SkirtsModified/Overlay_Images/WW_SK_REG_1_002.png"
                                },
                                {
                                    materialId: 1,
                                    url: "assets/processed/SkirtsModified/WW_SK_REG_1_003T.jpg",
                                    SK: "assets/processed/SkirtsModified/Overlay_Images/WW_SK_REG_1_003.png"
                                }
                            ]
                        },
                        {
                            id: 5,
                            itemName: "Skirts_SK2",
                            mainImageUrl: "assets/processed/SkirtsModified/Main_Image/WW_SK_2.jpg",
                            mainImageTh: "assets/processed/SkirtsModified/Main_Image/WW_SK_2_T.jpg",
                            positions: [
                                {
                                    posId: "SK",
                                    coordX1: "20",
                                    coordY1: "38",
                                    coordX2: "33",
                                    coordY2: "68"
                                }
                            ],
                            patterns: [
                                {
                                    materialId: 1,
                                    url: "assets/processed/SkirtsModified/WW_SK_REG_2_001T.jpg",
                                    SK: "assets/processed/SkirtsModified/Overlay_Images/WW_SK_REG_2_001.png"
                                },
                                {
                                    materialId: 1,
                                    url: "assets/processed/SkirtsModified/WW_SK_REG_2_002T.jpg",
                                    SK: "assets/processed/SkirtsModified/Overlay_Images/WW_SK_REG_2_002.png"
                                },
                                {
                                    materialId: 1,
                                    url: "assets/processed/SkirtsModified/WW_SK_REG_1_002T.jpg",
                                    SK: "assets/processed/SkirtsModified/Overlay_Images/WW_SK_REG_2_003.png"
                                }
                            ]
                        },
                        {
                            id: 6,
                            itemName: "WW_SK_3",
                            mainImageUrl: "assets/processed/SkirtsModified/Main_Image/WW_SK_3.jpg",
                            mainImageTh: "assets/processed/SkirtsModified/Main_Image/WW_SK_3_T.jpg",
                            positions: [
                                {
                                    posId: "SK",
                                    coordX1: "39",
                                    coordY1: "50",
                                    coordX2: "57",
                                    coordY2: "80"
                                }
                            ],
                            patterns: [
                                {
                                    materialId: 1,
                                    url: "assets/processed/SkirtsModified/WW_SK_REG_2_002T.jpg",
                                    SK: "assets/processed/SkirtsModified/Overlay_Images/WW_SK_REG_3_001.png"
                                },
                                {
                                    materialId: 1,
                                    url: "assets/processed/SkirtsModified/WW_SK_REG_2_001T.jpg",
                                    SK: "assets/processed/SkirtsModified/Overlay_Images/WW_SK_REG_3_002.png"
                                },
                                {
                                    materialId: 1,
                                    url: "assets/processed/SkirtsModified/WW_SK_REG_2_004T.jpg",
                                    SK: "assets/processed/SkirtsModified/Overlay_Images/WW_SK_REG_3_003.png"
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    };

**Comment by prashantgavhane** [comment]
How we parse the multi structure JSON file into CSV or EXCEL

**Comment by konklone** [comment]
Get rid of the `var tabMappings =` and try again. With that part, it's not valid JSON.
